### ISSUE TITLE
`ConstrainedReschedule` raises an error with reset

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit#10354]
### Environment

- **Qiskit Terra version**:  main
- **Python version**: 3.10.12
- **Operating system**: macOS 13.4.1

### What is happening?

`ConstrainedReschedule` raises `TranspilerError` with reset.

### How can we reproduce the issue?

```python
from qiskit import QuantumCircuit
from qiskit.providers.fake_provider import FakeBogotaV2
from qiskit.transpiler import PassManager
from qiskit.transpiler.passes import ALAPScheduleAnalysis, ConstrainedReschedule, TimeUnitConversion

backend = FakeBogotaV2()
target = backend.target
durations = target.durations()

circuit = QuantumCircuit(2)
circuit.cx(0, 1)
circuit.reset(0)

pm = PassManager(
    [
        TimeUnitConversion(durations),
        ALAPScheduleAnalysis(durations),
        ConstrainedReschedule(),
    ]
)

_ = pm.run(circuit)
```

output
```
Traceback (most recent call last):
  File "/Users/ima/tasks/3_2023/qiskit/terra/qiskit/transpiler/runningpassmanager.py", line 226, in wrapper
    return meth(*meth_args, **meth_kwargs)
  File "/Users/ima/tasks/3_2023/qiskit/terra/qiskit/transpiler/runningpassmanager.py", line 148, in run
    return super().run(
  File "/Users/ima/tasks/3_2023/qiskit/terra/qiskit/passmanager/passrunner.py", line 235, in run
    passmanager_ir = self._run_pass_generic(
  File "/Users/ima/tasks/3_2023/qiskit/terra/qiskit/passmanager/passrunner.py", line 190, in _run_pass_generic
    passmanager_ir = self._run_pass_generic(
  File "/Users/ima/tasks/3_2023/qiskit/terra/qiskit/passmanager/passrunner.py", line 151, in _run_pass_generic
    passmanager_ir = self._run_base_pass(
  File "/Users/ima/tasks/3_2023/qiskit/terra/qiskit/transpiler/runningpassmanager.py", line 188, in _run_base_pass
    pass_.run(FencedDAGCircuit(passmanager_ir))
  File "/Users/ima/tasks/3_2023/qiskit/terra/qiskit/transpiler/passes/scheduling/alignments/reschedule.py", line 241, in run
    self._push_node_back(dag, node)
  File "/Users/ima/tasks/3_2023/qiskit/terra/qiskit/transpiler/passes/scheduling/alignments/reschedule.py", line 122, in _push_node_back
    raise TranspilerError(f"Unknown operation type for {repr(node)}.")
qiskit.transpiler.exceptions.TranspilerError: "Unknown operation type for DAGOpNode(op=Instruction(name='reset', num_qubits=1, num_clbits=0, params=[]), qargs=(Qubit(QuantumRegister(2, 'q'), 0),), cargs=())."

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ima/tasks/3_2023/qiskit/terra/qiskit/transpiler/passmanager.py", line 447, in wrapper
    return meth(*meth_args, **meth_kwargs)
  File "/Users/ima/tasks/3_2023/qiskit/terra/qiskit/transpiler/passmanager.py", line 154, in run
    return super().run(
  File "/Users/ima/tasks/3_2023/qiskit/terra/qiskit/passmanager/passmanager.py", line 225, in run
    out_program = self._run_single_circuit(in_programs[0], callback, **metadata)
  File "/Users/ima/tasks/3_2023/qiskit/terra/qiskit/transpiler/passmanager.py", line 173, in _run_single_circuit
    out_program = pass_runner.run(input_program, callback=callback, **metadata)
  File "/Users/ima/tasks/3_2023/qiskit/terra/qiskit/transpiler/runningpassmanager.py", line 228, in wrapper
    raise TranspilerError(ex.message) from ex
qiskit.transpiler.exceptions.TranspilerError: "Unknown operation type for DAGOpNode(op=Instruction(name='reset', num_qubits=1, num_clbits=0, params=[]), qargs=(Qubit(QuantumRegister(2, 'q'), 0),), cargs=())."

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ima/tasks/3_2023/ntc/ntc-ibm-programs/tmp/432-min.py", line 22, in <module>
    _ = pm.run(circuit)
  File "/Users/ima/tasks/3_2023/qiskit/terra/qiskit/transpiler/passmanager.py", line 449, in wrapper
    raise TranspilerError(ex.message) from ex
qiskit.transpiler.exceptions.TranspilerError: "Unknown operation type for DAGOpNode(op=Instruction(name='reset', num_qubits=1, num_clbits=0, params=[]), qargs=(Qubit(QuantumRegister(2, 'q'), 0),), cargs=())."
```

### What should happen?

If `ConstrainedReschedule` does not support reset instruction, it would be great if the error message is more comprehensive rather than "Unknown operation type...".

**Comment by alexanderivrii** [comment]
Thanks @t-imamichi. It seems that running `ConstrainedReschedule` on circuits with resets became disallowed in my PR #10007, in particular due to the following code:
```
if isinstance(node.op, Gate):
    alignment = self.pulse_align
elif isinstance(node.op, Measure):
    alignment = self.acquire_align
elif isinstance(node.op, Delay) or getattr(node.op, "_directive", False):
    # Directive or delay. These can start at arbitrary time.
    alignment = None
else:
    raise TranspilerError(f"Unknown operation type for {repr(node)}.")
```
I don't know whether resets cannot be supported, or whether resets behave like `Measure`, or whether resets can start at arbitrary time. 

I agree that the error message is not very helpful.

**Comment by t-imamichi** [comment]
Thank you for your information!
