### ISSUE TITLE
QuantumCircuit qasm2 dumps generates wrong OpenQASM code

### ISSUE THREAD

**Issue by sergeysalata** [Qiskit/qiskit#11508]
### Environment

- **Qiskit Terra version**: 
- **Python version**: 
- **Operating system**: 

### What is happening?

When exporting QuantumCircuit to OpenQASM U gate exported as 'u' instead of 'U' this leads to error when importing generated OpenQASM code using qasm2.loads()

Step to reproduce:
Run program:

```
from qiskit import qasm2
from qiskit import QuantumRegister, QuantumCircuit
q = QuantumRegister(1, "q")
qc = QuantumCircuit(q)
qc.u(0.3, 0.2, 0.1, q[0])
qq =  qasm2.dumps(qc);
print(qq);
circuit = qasm2.loads( qq );
```
Output:
**OPENQASM 2.0;
include "qelib1.inc";
qreg q[1];
u(0.3,0.2,0.1) q[0];
Traceback (most recent call last):
File "C:\work\1\python\tele2.py", line 12, in
circuit = qasm2.loads( qq );
File "C:\work\quantum\qiskit\lib\site-packages\qiskit\qasm2_init_.py", line 604, in loads
return _parse.from_bytecode(
File "C:\work\quantum\qiskit\lib\site-packages\qiskit\qasm2\parse.py", line 214, in from_bytecode
for op in bc:
qiskit.qasm2.exceptions.QASM2ParseError: ":4,0: 'u' is not defined in this scope"**

But if replace in generated code last line to "U(0.3,0.2,0.1) q[0];" then code imported correctly

### How can we reproduce the issue?

Run program
```
from qiskit import qasm2
from qiskit import QuantumRegister, QuantumCircuit
q = QuantumRegister(1, "q")
qc = QuantumCircuit(q)
qc.u(0.3, 0.2, 0.1, q[0])
qq =  qasm2.dumps(qc);
print(qq);
circuit = qasm2.loads( qq );
```

### What should happen?

There should be no error when import just exported OpenQASM code

### Any suggestions?

 replace in generated code last line to "U(0.3,0.2,0.1) q[0];" then code imported correctly

**Comment by jakelishman** [comment]
Thanks - this is (unfortunately) a known current issue, where the OpenQASM 2 export hallucinates some additional non-standard gates in `qelib1.inc`; you can see some discussion in #4312 (nearly four years ago! ...) and our general plan for how we're going to fix it in #10737.

For the time being as a workaround, you can tell Qiskit's OpenQASM 2 loader about all the extra gates like this:
```python
from qiskit import qasm2
from qiskit import QuantumRegister, QuantumCircuit
q = QuantumRegister(1, "q")
qc = QuantumCircuit(q)
qc.u(0.3, 0.2, 0.1, q[0])
qq =  qasm2.dumps(qc)

# ... just your code so far.  Now:

qasm2.loads(qq, custom_instructions=qasm2.LEGACY_CUSTOM_INSTRUCTIONS)
```

The extra `custom_instructions=qasm2.LEGACY_CUSTOM_INSTRUCTIONS` tells the parser about all the extra gates that the exporter used without properly defining.  The real fix from our side will be to make the exporter do the correct thing in the first place.
