### ISSUE TITLE
TestTwoQubitWeylDecompositionSpecialization test failures in CI

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit#11676]
### Environment

- **Qiskit version**: main
- **Python version**: 3.12.1
- **Operating system**: Linux

### What is happening?

There are several two qubit weyl decomposition tests failing in CI occasionally now. This has happened twice that I've observed and my guess is it's a numeric precision issue coming from some environment difference. Examples of the failures are:

```
test.python.synthesis.test_synthesis.TestTwoQubitWeylDecompositionSpecialization.test_weyl_specialize_fsim_abb
--------------------------------------------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/tmp/terra-tests/test/python/synthesis/test_synthesis.py", line 920, in test_weyl_specialize_fsim_abb
    self.check_two_qubit_weyl_specialization(

      File "/tmp/terra-tests/test/python/synthesis/test_synthesis.py", line 236, in check_two_qubit_weyl_specialization
    self.assertRoundTrip(decomp)

      File "/tmp/terra-tests/test/python/synthesis/test_synthesis.py", line 168, in assertRoundTrip
    self.assertEqual(weyl1.a, weyl2.a, msg=msg_base)

      File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/unittest/case.py", line 887, in assertEqual
    assertion_func(first, second, msg=msg)

      File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/unittest/case.py", line 880, in _baseAssertEqual
    raise self.failureException(msg)

    AssertionError: 0.44600000000000006 != 0.44599999999999995 : weyl1:
TwoQubitWeylfSimabbEquiv.from_bytes(
    # TwoQubitWeylfSimabbEquiv(
    # 	global phase: 0.32841
    # 	     ┌─────────────┐┌────────────┐┌────────────┐┌──────────────┐┌──────────────┐             ┌────────────┐┌─────────────┐┌─────────────┐
    # 	q_0: ┤ Rx(-1.5717) ├┤ Ry(1.9416) ├┤ Rx(1.1555) ├┤0             ├┤0             ├─■───────────┤ Rx(3.1039) ├┤ Ry(0.78779) ├┤ Rx(0.48002) ├
    # 	     ├─────────────┤├────────────┤└────────────┘│  Rxx(-0.892) ││  Ryy(-0.266) │ │ZZ(-0.266) ├────────────┤├─────────────┤└┬────────────┤
    # 	q_1: ┤ Rx(0.49803) ├┤ Ry(3.0773) ├──────────────┤1             ├┤1             ├─■───────────┤ Rx(2.4426) ├┤ Ry(0.44615) ├─┤ Rx(1.0949) ├
    # 	     └─────────────┘└────────────┘              └──────────────┘└──────────────┘             └────────────┘└─────────────┘ └────────────┘
    # )
    b'k05VTVBZAQB2AHsnZGVzY3InOiAnPGMxNicsICdmb3J0cmFuX29yZGVyJzogRmFsc2UsICdzaGFw'
    b'ZSc6ICg0LCA0KSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg'
    b'ICAgICAgICAgICAgIAo2RMfF3a3KP+6JgsZtI82/WJD8/Oxy3L/BSfrElYfov5B2a+3dHNA/k+re'
    b'dhVrxD+Q9iraAF2vP3i7F1U/BMW/DjsVDEOg4L/xogKdLZDiPwnOXmcrbMC/HcFQwJQ40r+ATs4U'
    b'aQZiv4ciprqAs8M/+kTG6/Rz37/S/s6o0nbGP2F9q76sc9S/LOzqd4xY17+Oedy3xI27v+wN8Rog'
    b'wMC/ctH+Xaik1L910uHAEnm7P3P4vECYjdM/P27IwCc85z9hszzDSX3Kvxnu21xoOMK/wF2Ok0r0'
    b'0j8UCeexxy2eP4ppXnhKA+w/cGFqnakks7/YtuVMk+ubP0bgoTLZmtE/',
    requested_fidelity=0.999,
    calculated_fidelity=0.9998400133327289,
    actual_fidelity=0.9998400133327291,
    abc=(0.44600000000000006, 0.133, 0.133))
weyl2:
TwoQubitWeylfSimabbEquiv.from_bytes(
    # TwoQubitWeylfSimabbEquiv(
    # 	global phase: 0.32841
    # 	     ┌─────────────┐┌────────────┐┌────────────┐┌──────────────┐┌──────────────┐             ┌────────────┐┌─────────────┐┌─────────────┐
    # 	q_0: ┤ Rx(-1.5717) ├┤ Ry(1.9416) ├┤ Rx(1.1555) ├┤0             ├┤0             ├─■───────────┤ Rx(3.1039) ├┤ Ry(0.78779) ├┤ Rx(0.48002) ├
    # 	     ├─────────────┤├────────────┤└────────────┘│  Rxx(-0.892) ││  Ryy(-0.266) │ │ZZ(-0.266) ├────────────┤├─────────────┤└┬────────────┤
    # 	q_1: ┤ Rx(0.49803) ├┤ Ry(3.0773) ├──────────────┤1             ├┤1             ├─■───────────┤ Rx(2.4426) ├┤ Ry(0.44615) ├─┤ Rx(1.0949) ├
    # 	     └─────────────┘└────────────┘              └──────────────┘└──────────────┘             └────────────┘└─────────────┘ └────────────┘
    # )
    b'k05VTVBZAQB2AHsnZGVzY3InOiAnPGMxNicsICdmb3J0cmFuX29yZGVyJzogRmFsc2UsICdzaGFw'
    b'ZSc6ICg0LCA0KSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg'
    b'ICAgICAgICAgICAgIAo2RMfF3a3KP+6JgsZtI82/WJD8/Oxy3L/BSfrElYfov5B2a+3dHNA/k+re'
    b'dhVrxD+Q9iraAF2vP3i7F1U/BMW/DjsVDEOg4L/xogKdLZDiPwnOXmcrbMC/HcFQwJQ40r+ATs4U'
    b'aQZiv4ciprqAs8M/+kTG6/Rz37/S/s6o0nbGP2F9q76sc9S/LOzqd4xY17+Oedy3xI27v+wN8Rog'
    b'wMC/ctH+Xaik1L910uHAEnm7P3P4vECYjdM/P27IwCc85z9hszzDSX3Kvxnu21xoOMK/wF2Ok0r0'
    b'0j8UCeexxy2eP4ppXnhKA+w/cGFqnakks7/YtuVMk+ubP0bgoTLZmtE/',
    requested_fidelity=0.999,
    calculated_fidelity=0.9998400133327289,
    actual_fidelity=0.9998400133327291,
    abc=(0.44599999999999995, 0.133, 0.133))
```

and

```
test.python.synthesis.test_synthesis.TestTwoQubitWeylDecompositionSpecialization.test_weyl_specialize_swap
----------------------------------------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/tmp/terra-tests/test/python/synthesis/test_synthesis.py", line 850, in test_weyl_specialize_swap
    self.check_two_qubit_weyl_specialization(

      File "/tmp/terra-tests/test/python/synthesis/test_synthesis.py", line 236, in check_two_qubit_weyl_specialization
    self.assertRoundTrip(decomp)

      File "/tmp/terra-tests/test/python/synthesis/test_synthesis.py", line 172, in assertRoundTrip
    self.assertEqual(maxdiff, 0, msg=f"K1l matrix differs by {maxdiff}" + msg_base)

      File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/unittest/case.py", line 887, in assertEqual
    assertion_func(first, second, msg=msg)

      File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/unittest/case.py", line 880, in _baseAssertEqual
    raise self.failureException(msg)

    AssertionError: 2.220446049250313e-16 != 0 : K1l matrix differs by 2.220446049250313e-16weyl1:
TwoQubitWeylSWAPEquiv.from_bytes(
    # TwoQubitWeylSWAPEquiv(
    # 	global phase: 5.2504
    # 	        ┌──────────────┐┌─────────────┐┌─────────────┐
    # 	q_0: ─X─┤ Rz(-0.78295) ├┤ Ry(0.60112) ├┤ Rz(0.70223) ├
    # 	      │ └┬────────────┬┘└─┬──────────┬┘└┬────────────┤
    # 	q_1: ─X──┤ Rz(1.8994) ├───┤ Ry(2.23) ├──┤ Rz(1.0922) ├
    # 	         └────────────┘   └──────────┘  └────────────┘
    # )
    b'k05VTVBZAQB2AHsnZGVzY3InOiAnPGMxNicsICdmb3J0cmFuX29yZGVyJzogRmFsc2UsICdzaGFw'
    b'ZSc6ICg0LCA0KSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg'
    b'ICAgICAgICAgICAgIAr/MJVgwjDVP4PQmA/3Q9A/KJHAxsfd5j/HTOBMeoXev8VQGt7+zMC/ZBle'
    b'teFHkD90cDRH4LmsvzTNUFtIlNA/SFjTI/nNnz8Cw04ghnzAP6apD3AN3tA/QJYc3lCxmz8hQjur'
    b'CbbWP7L/SXZwR80/5kDfHOF85T97HqAKvAbhv9BdszslC8O/NZIS4usO6z9ipcWwwnjXv1YZ1Qp4'
    b'2Mm/hmfkXjnSw7+TiQc9Cc7Lv2CpvPiuVb8/0MW0UxODo7/P9yw34IvKv3ZSXZ/Nc8U/eqLGSbjq'
    b'pr+o6LUT9M++v2RoL/F9obS/uDX/0fhG6z/upTbqdrPYv64U6PkqTMa/',
    requested_fidelity=0.999,
    calculated_fidelity=0.9999768002893319,
    actual_fidelity=0.9999768002893321,
    abc=(0.7853981633974483, 0.7853981633974483, 0.7853981633974483))
weyl2:
TwoQubitWeylSWAPEquiv.from_bytes(
    # TwoQubitWeylSWAPEquiv(
    # 	global phase: 5.2504
    # 	        ┌──────────────┐┌─────────────┐┌─────────────┐
    # 	q_0: ─X─┤ Rz(-0.78295) ├┤ Ry(0.60112) ├┤ Rz(0.70223) ├
    # 	      │ └┬────────────┬┘└─┬──────────┬┘└┬────────────┤
    # 	q_1: ─X──┤ Rz(1.8994) ├───┤ Ry(2.23) ├──┤ Rz(1.0922) ├
    # 	         └────────────┘   └──────────┘  └────────────┘
    # )
    b'k05VTVBZAQB2AHsnZGVzY3InOiAnPGMxNicsICdmb3J0cmFuX29yZGVyJzogRmFsc2UsICdzaGFw'
    b'ZSc6ICg0LCA0KSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg'
    b'ICAgICAgICAgICAgIAr/MJVgwjDVP4PQmA/3Q9A/KJHAxsfd5j/HTOBMeoXev8VQGt7+zMC/ZBle'
    b'teFHkD90cDRH4LmsvzTNUFtIlNA/SFjTI/nNnz8Cw04ghnzAP6apD3AN3tA/QJYc3lCxmz8hQjur'
    b'CbbWP7L/SXZwR80/5kDfHOF85T97HqAKvAbhv9BdszslC8O/NZIS4usO6z9ipcWwwnjXv1YZ1Qp4'
    b'2Mm/hmfkXjnSw7+TiQc9Cc7Lv2CpvPiuVb8/0MW0UxODo7/P9yw34IvKv3ZSXZ/Nc8U/eqLGSbjq'
    b'pr+o6LUT9M++v2RoL/F9obS/uDX/0fhG6z/upTbqdrPYv64U6PkqTMa/',
    requested_fidelity=0.999,
    calculated_fidelity=0.9999768002893319,
    actual_fidelity=0.9999768002893317,
    abc=(0.7853981633974483, 0.7853981633974483, 0.7853981633974483))
```

### How can we reproduce the issue?

Have CI fail, such as: https://dev.azure.com/qiskit-ci/qiskit/_build/results?buildId=53980&view=logs&jobId=42553bb7-c640-5e19-486b-534ade7d1f3b&j=42553bb7-c640-5e19-486b-534ade7d1f3b&t=ec81b5c9-a7aa-58a8-95bd-450209a80da7 (this link will expire eventually, but the failure output is above)

### What should happen?

The tests should pass reliably on all supported platforms.

**Comment by 1ucian0** [comment]
probably related, `test.python.synthesis.test_synthesis.TestTwoQubitWeylDecompositionSpecialization.test_weyl_specialize_mirror_ctrl` fails very similarly https://dev.azure.com/qiskit-ci/qiskit/_build/results?buildId=54080&view=logs&jobId=96a5c06e-ab32-5618-636f-7d7f3fce6d94&j=96a5c06e-ab32-5618-636f-7d7f3fce6d94&t=4dff3c95-38ec-5978-7d5b-48fc44b08b5d

**Comment by ElePT** [comment]
I'm finding relatively consistent (5/5 last CI runs in https://github.com/Qiskit/qiskit/pull/11755) failures in `test.python.synthesis.test_synthesis.TestTwoQubitWeylDecompositionSpecialization.test_weyl_specialize_fsim_abb` too: https://dev.azure.com/qiskit-ci/qiskit/_build/results?buildId=54525&view=logs&j=80763036-ed5e-5d3e-143d-8ae8edc29f03&t=fbe37352-a804-5c65-db48-e3b769f64c22&l=16705

```
Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/tmp/terra-tests/test/python/synthesis/test_synthesis.py", line 912, in test_weyl_specialize_fsim_abb
    self.check_two_qubit_weyl_specialization(

      File "/tmp/terra-tests/test/python/synthesis/test_synthesis.py", line 233, in check_two_qubit_weyl_specialization
    decomp = decomposer(target_unitary, fidelity=fidelity)

      File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)

      File "/tmp/terra-tests/test/python/synthesis/test_synthesis.py", line 150, in assertDebugOnly
    self.assertLessEqual(

      File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/unittest/case.py", line 1304, in assertLessEqual
    self.fail(self._formatMessage(msg, standardMsg))

      File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/unittest/case.py", line 753, in fail
    raise self.failureException(msg)

    AssertionError: 30 not less than or equal to 10 : Unexpected logging entry: WARNING:qiskit.synthesis.two_qubit.two_qubit_decompose:Requested fidelity different from actual by 0.5617572836733848
```
The difference in fidelity seems to oscillate between these 2 values:

```
Requested fidelity different from actual by 0.5617572836733848
Requested fidelity different from actual by 0.5617572836733773
```

**Comment by levbishop** [comment]
Now that #11797 and #11798 have landed it will be good to capture more failing examples here (along with the numpy versioning info) and hopefully there's a pattern to spot

**Comment by jakelishman** [comment]
Ok, the recent Numpy / Python theories just went out the window because it's just happened on Numpy 1.24.4 with Python 3.8: https://dev.azure.com/qiskit-ci/qiskit/_build/results?buildId=55092&view=logs&j=80763036-ed5e-5d3e-143d-8ae8edc29f03&t=fbe37352-a804-5c65-db48-e3b769f64c22.  (I've retained that log, so it should stick around.)

The VM in question has a SkylakeX.  Copying in the relevant output from the logs:
```
2024-02-29T20:22:40.2793515Z openblas64__info:
2024-02-29T20:22:40.2794126Z     libraries = ['openblas64_', 'openblas64_']
2024-02-29T20:22:40.2794383Z     library_dirs = ['/usr/local/lib']
2024-02-29T20:22:40.2794515Z     language = c
2024-02-29T20:22:40.2794763Z     define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
2024-02-29T20:22:40.2795007Z     runtime_library_dirs = ['/usr/local/lib']
2024-02-29T20:22:40.2795135Z blas_ilp64_opt_info:
2024-02-29T20:22:40.2795324Z     libraries = ['openblas64_', 'openblas64_']
2024-02-29T20:22:40.2795505Z     library_dirs = ['/usr/local/lib']
2024-02-29T20:22:40.2795619Z     language = c
2024-02-29T20:22:40.2795873Z     define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
2024-02-29T20:22:40.2796096Z     runtime_library_dirs = ['/usr/local/lib']
2024-02-29T20:22:40.2796234Z openblas64__lapack_info:
2024-02-29T20:22:40.2796418Z     libraries = ['openblas64_', 'openblas64_']
2024-02-29T20:22:40.2796603Z     library_dirs = ['/usr/local/lib']
2024-02-29T20:22:40.2796717Z     language = c
2024-02-29T20:22:40.2797001Z     define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
2024-02-29T20:22:40.2797239Z     runtime_library_dirs = ['/usr/local/lib']
2024-02-29T20:22:40.2797377Z lapack_ilp64_opt_info:
2024-02-29T20:22:40.2797561Z     libraries = ['openblas64_', 'openblas64_']
2024-02-29T20:22:40.2797746Z     library_dirs = ['/usr/local/lib']
2024-02-29T20:22:40.2797860Z     language = c
2024-02-29T20:22:40.2798129Z     define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
2024-02-29T20:22:40.2798372Z     runtime_library_dirs = ['/usr/local/lib']
2024-02-29T20:22:40.2798514Z Supported SIMD extensions in this NumPy install:
2024-02-29T20:22:40.2798660Z     baseline = SSE,SSE2,SSE3
2024-02-29T20:22:40.2798817Z     found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2,AVX512F,AVX512CD,AVX512_SKX
2024-02-29T20:22:40.2799013Z     not found = AVX512_KNL,AVX512_KNM,AVX512_CLX,AVX512_CNL,AVX512_ICL
2024-02-29T20:22:40.2799247Z [{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
2024-02-29T20:22:40.2799441Z                       'found': ['SSSE3',
2024-02-29T20:22:40.2799603Z                                 'SSE41',
2024-02-29T20:22:40.2799955Z                                 'POPCNT',
2024-02-29T20:22:40.2800108Z                                 'SSE42',
2024-02-29T20:22:40.2800254Z                                 'AVX',
2024-02-29T20:22:40.2800414Z                                 'F16C',
2024-02-29T20:22:40.2800561Z                                 'FMA3',
2024-02-29T20:22:40.2800719Z                                 'AVX2',
2024-02-29T20:22:40.2800873Z                                 'AVX512F',
2024-02-29T20:22:40.2801041Z                                 'AVX512CD',
2024-02-29T20:22:40.2801201Z                                 'AVX512_SKX'],
2024-02-29T20:22:40.2801385Z                       'not_found': ['AVX512_KNL',
2024-02-29T20:22:40.2801556Z                                     'AVX512_KNM',
2024-02-29T20:22:40.2801845Z                                     'AVX512_CLX',
2024-02-29T20:22:40.2802009Z                                     'AVX512_CNL',
2024-02-29T20:22:40.2802173Z                                     'AVX512_ICL']}},
2024-02-29T20:22:40.2802345Z  {'architecture': 'SkylakeX',
2024-02-29T20:22:40.2802643Z   'filepath': '/home/vsts/work/1/s/test-job/lib/python3.8/site-packages/numpy.libs/libopenblas64_p-r0-15028c96.3.21.so',
2024-02-29T20:22:40.2802867Z   'internal_api': 'openblas',
2024-02-29T20:22:40.2803020Z   'num_threads': 2,
2024-02-29T20:22:40.2803179Z   'prefix': 'libopenblas',
2024-02-29T20:22:40.2803342Z   'threading_layer': 'pthreads',
2024-02-29T20:22:40.2803505Z   'user_api': 'blas',
2024-02-29T20:22:40.2803658Z   'version': '0.3.21'}]
2024-02-29T20:22:40.3661396Z /tmp/terra-tests ~/work/1/s
2024-02-29T20:22:40.3810428Z PYTHONHASHSEED=130251549
```

Failure:
```
2024-02-29T20:31:26.4426072Z test.python.synthesis.test_synthesis.TestTwoQubitWeylDecompositionSpecialization.test_weyl_specialize_fsim_abb
2024-02-29T20:31:26.4426483Z --------------------------------------------------------------------------------------------------------------
2024-02-29T20:31:26.4426970Z 
2024-02-29T20:31:26.4427155Z Captured traceback:
2024-02-29T20:31:26.4427356Z ~~~~~~~~~~~~~~~~~~~
2024-02-29T20:31:26.4427564Z     Traceback (most recent call last):
2024-02-29T20:31:26.4427698Z 
2024-02-29T20:31:26.4428053Z       File "/tmp/terra-tests/test/python/synthesis/test_synthesis.py", line 912, in test_weyl_specialize_fsim_abb
2024-02-29T20:31:26.4428321Z     self.check_two_qubit_weyl_specialization(
2024-02-29T20:31:26.4428476Z 
2024-02-29T20:31:26.4428813Z       File "/tmp/terra-tests/test/python/synthesis/test_synthesis.py", line 256, in check_two_qubit_weyl_specialization
2024-02-29T20:31:26.4429086Z     self.assertRoundTrip(decomp2)
2024-02-29T20:31:26.4429221Z 
2024-02-29T20:31:26.4429536Z       File "/tmp/terra-tests/test/python/synthesis/test_synthesis.py", line 167, in assertRoundTrip
2024-02-29T20:31:26.4429806Z     self.assertEqual(weyl1.a, weyl2.a, msg=msg_base)
2024-02-29T20:31:26.4429952Z 
2024-02-29T20:31:26.4430192Z       File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/unittest/case.py", line 912, in assertEqual
2024-02-29T20:31:26.4430452Z     assertion_func(first, second, msg=msg)
2024-02-29T20:31:26.4430590Z 
2024-02-29T20:31:26.4430846Z       File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
2024-02-29T20:31:26.4431105Z     raise self.failureException(msg)
2024-02-29T20:31:26.4431252Z 
2024-02-29T20:31:26.4431458Z     AssertionError: 0.43700000000000006 != 0.43699999999999994 : weyl1:
2024-02-29T20:31:26.4431696Z TwoQubitWeylfSimabbEquiv.from_bytes(
2024-02-29T20:31:26.4431906Z     # TwoQubitWeylfSimabbEquiv(
2024-02-29T20:31:26.4432114Z     # 	global phase: 0.32841
2024-02-29T20:31:26.4432549Z     # 	     ┌─────────────┐┌────────────┐┌────────────┐┌──────────────┐┌──────────────┐             ┌────────────┐┌─────────────┐┌─────────────┐
2024-02-29T20:31:26.4432987Z     # 	q_0: ┤ Rx(-1.5717) ├┤ Ry(1.9416) ├┤ Rx(1.1555) ├┤0             ├┤0             ├─■───────────┤ Rx(3.1039) ├┤ Ry(0.78779) ├┤ Rx(0.48002) ├
2024-02-29T20:31:26.4433448Z     # 	     ├─────────────┤├────────────┤└────────────┘│  Rxx(-0.874) ││  Ryy(-0.303) │ │ZZ(-0.303) ├────────────┤├─────────────┤└┬────────────┤
2024-02-29T20:31:26.4433886Z     # 	q_1: ┤ Rx(0.49803) ├┤ Ry(3.0773) ├──────────────┤1             ├┤1             ├─■───────────┤ Rx(2.4426) ├┤ Ry(0.44615) ├─┤ Rx(1.0949) ├
2024-02-29T20:31:26.4434432Z     # 	     └─────────────┘└────────────┘              └──────────────┘└──────────────┘             └────────────┘└─────────────┘ └────────────┘
2024-02-29T20:31:26.4434645Z     # )
2024-02-29T20:31:26.4434953Z     b'k05VTVBZAQB2AHsnZGVzY3InOiAnPGMxNicsICdmb3J0cmFuX29yZGVyJzogRmFsc2UsICdzaGFw'
2024-02-29T20:31:26.4435316Z     b'ZSc6ICg0LCA0KSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg'
2024-02-29T20:31:26.4435674Z     b'ICAgICAgICAgICAgIArTMzZU31PKP+nSG0/0wsy/1pLLmFFd3L/yQfpYNPHovzNScZmz7cw/v+9s'
2024-02-29T20:31:26.4436025Z     b'2csPwj/vQZQPoGewP1SB0kUfesW/kUsXBFA64L9egbafh4viP2kmx7dWZr+/bp67UHuJ0r/WDJ+s'
2024-02-29T20:31:26.4436473Z     b'0MSHv91nmy6kh8I/lCzPukMT4L9MleEBK87HP534pGCzWdW/Lk2M2y+517+8VdsFL4m4v+3nhaqq'
2024-02-29T20:31:26.4436827Z     b'3cC/4GX9mBgX1b9EI6NwjFa6P9KliVRl19M/zhMSIDfX5j+zq5tZ+evKvzsurnSbqMK/BK18Ikru'
2024-02-29T20:31:26.4437171Z     b'0D/Q+/3PtJiYP8TCKGAkVuw/+Bs5eMhesb884+rnbGSbP86FtTHZd9E/',
2024-02-29T20:31:26.4437396Z     requested_fidelity=None,
2024-02-29T20:31:26.4437616Z     calculated_fidelity=0.99999640000675,
2024-02-29T20:31:26.4437830Z     actual_fidelity=0.99999640000675,
2024-02-29T20:31:26.4438071Z     abc=(0.43700000000000006, 0.1515000000000004, 0.1515000000000004))
2024-02-29T20:31:26.4438282Z weyl2:
2024-02-29T20:31:26.4438485Z TwoQubitWeylfSimabbEquiv.from_bytes(
2024-02-29T20:31:26.4438696Z     # TwoQubitWeylfSimabbEquiv(
2024-02-29T20:31:26.4438903Z     # 	global phase: 0.32841
2024-02-29T20:31:26.4439303Z     # 	     ┌─────────────┐┌────────────┐┌────────────┐┌──────────────┐┌──────────────┐             ┌────────────┐┌─────────────┐┌─────────────┐
2024-02-29T20:31:26.4439845Z     # 	q_0: ┤ Rx(-1.5717) ├┤ Ry(1.9416) ├┤ Rx(1.1555) ├┤0             ├┤0             ├─■───────────┤ Rx(3.1039) ├┤ Ry(0.78779) ├┤ Rx(0.48002) ├
2024-02-29T20:31:26.4440287Z     # 	     ├─────────────┤├────────────┤└────────────┘│  Rxx(-0.874) ││  Ryy(-0.303) │ │ZZ(-0.303) ├────────────┤├─────────────┤└┬────────────┤
2024-02-29T20:31:26.4440757Z     # 	q_1: ┤ Rx(0.49803) ├┤ Ry(3.0773) ├──────────────┤1             ├┤1             ├─■───────────┤ Rx(2.4426) ├┤ Ry(0.44615) ├─┤ Rx(1.0949) ├
2024-02-29T20:31:26.4441185Z     # 	     └─────────────┘└────────────┘              └──────────────┘└──────────────┘             └────────────┘└─────────────┘ └────────────┘
2024-02-29T20:31:26.4441393Z     # )
2024-02-29T20:31:26.4441702Z     b'k05VTVBZAQB2AHsnZGVzY3InOiAnPGMxNicsICdmb3J0cmFuX29yZGVyJzogRmFsc2UsICdzaGFw'
2024-02-29T20:31:26.4442052Z     b'ZSc6ICg0LCA0KSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg'
2024-02-29T20:31:26.4442410Z     b'ICAgICAgICAgICAgIArTMzZU31PKP+nSG0/0wsy/1pLLmFFd3L/yQfpYNPHovzNScZmz7cw/v+9s'
2024-02-29T20:31:26.4442775Z     b'2csPwj/vQZQPoGewP1SB0kUfesW/kUsXBFA64L9egbafh4viP2kmx7dWZr+/bp67UHuJ0r/WDJ+s'
2024-02-29T20:31:26.4443137Z     b'0MSHv91nmy6kh8I/lCzPukMT4L9MleEBK87HP534pGCzWdW/Lk2M2y+517+8VdsFL4m4v+3nhaqq'
2024-02-29T20:31:26.4443558Z     b'3cC/4GX9mBgX1b9EI6NwjFa6P9KliVRl19M/zhMSIDfX5j+zq5tZ+evKvzsurnSbqMK/BK18Ikru'
2024-02-29T20:31:26.4443899Z     b'0D/Q+/3PtJiYP8TCKGAkVuw/+Bs5eMhesb884+rnbGSbP86FtTHZd9E/',
2024-02-29T20:31:26.4444126Z     requested_fidelity=None,
2024-02-29T20:31:26.4444343Z     calculated_fidelity=0.99999640000675,
2024-02-29T20:31:26.4444559Z     actual_fidelity=0.9999964000067504,
2024-02-29T20:31:26.4444805Z     abc=(0.43699999999999994, 0.1515000000000004, 0.1515000000000004))
```

**Comment by mtreinish** [comment]
I think we can probably close this as fixed by #11946 since I haven't seen this since that merged. However, I know #13176 is failing the merge queue with this issue but on the `stable/0.46` branch which doesn't have #11946. That's (hopefully) the last PR before we retire the 0.46.x branch so I'll wait to close this until that release goes out.

**Comment by mtreinish** [comment]
I'm going to close this now based on my above comment
