### ISSUE TITLE
CommutationChecker fails if an operation name is not ascii-encodable.

### ISSUE THREAD

**Issue by airwoodix** [Qiskit/qiskit#12051]
### Environment

- **Qiskit version**: 1.0.0
- **Python version**:  3.12.1
- **Operating system**:  Linux

### What is happening?

`CommutationChecker` fails if an operation name is not ascii-encodable.

### How can we reproduce the issue?

```python
from math import pi

from qiskit import QuantumCircuit
from qiskit.circuit import CommutationChecker

sub = QuantumCircuit(2, name="non-ascii-name-π")
sub.rxx(pi, 0, 1)

qc = QuantumCircuit(2)
qc.append(sub.to_instruction(), (0, 1))
qc.rxx(pi, 0, 1)

op0 = qc.data[0].operation
qargs0 = qc.data[0].qubits

op1 = qc.data[1].operation
qargs1 = qc.data[1].qubits

cc = CommutationChecker()
cc.commute(op0, qargs0, [], op1, qargs1, [])
```

Fails with:

```
Traceback (most recent call last):
  File "repro.py", line 20, in <module>
    cc.commute(op0, qargs0, [], op1, qargs1, [])
  File ".../python3.12/site-packages/qiskit/circuit/commutation_checker.py", line 92, in commute
    first_op_tuple, second_op_tuple = _order_operations(
                                      ^^^^^^^^^^^^^^^^^^
  File ".../python3.12/site-packages/qiskit/circuit/commutation_checker.py", line 317, in _order_operations
    if _persistent_id(op1.name) < _persistent_id(op2.name)
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.12/site-packages/qiskit/circuit/commutation_checker.py", line 288, in _persistent_id
    return int.from_bytes(bytes(op_name, encoding="ascii"), byteorder="big", signed=True)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode character '\u03c0' in position 15: ordinal not in range(128)
```

### What should happen?

The reproduction script should not fail.

### Any suggestions?

Changing the encoding of the bytes used to compute the `persistent_id` to e.g. `utf-8` solves the issue.

**Comment by sbrandhsn** [comment]
Hi Etienne, thanks for this clearly written issue - I must have missed that gates might have a non-ascii name. :-) -Sebastian
