### ISSUE TITLE
`BackendSampler` (V1) fails to run with empty classical register

### ISSUE THREAD

**Issue by garrison** [Qiskit/qiskit#12053]
### Environment

- **Qiskit version**: `main`
- **Python version**: 3.11
- **Operating system**: 

### What is happening?

The `BackendSampler` primitive fails to run if provided a circuit where the classical register contains zero bits.  (Note that currently `BackendSampler` only supports a single classical register -- see #11967.)

### How can we reproduce the issue?

```python
from qiskit.circuit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.primitives import BackendSampler
from qiskit_aer import AerSimulator

qreg = QuantumRegister(1)
creg = ClassicalRegister(0)
qc = QuantumCircuit(qreg, creg)
qc.h(0)

backend = AerSimulator()
sampler = BackendSampler(backend=backend)
sampler.run([qc], shots=1024).result()
```

raises the traceback

```
Traceback (most recent call last):
  File "/home/garrison/Qiskit/qiskit/empty-creg-backendsamplerv1.py", line 13, in <module>
    sampler.run([qc], shots=1024).result()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/garrison/Qiskit/qiskit/qiskit/primitives/base/base_sampler.py", line 131, in run
    circuits, parameter_values = validation._validate_sampler_args(circuits, parameter_values)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/garrison/Qiskit/qiskit/qiskit/primitives/base/validation.py", line 87, in _validate_sampler_args
    circuits = _validate_circuits(circuits, requires_measure=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/garrison/Qiskit/qiskit/qiskit/primitives/base/validation.py", line 117, in _validate_circuits
    raise ValueError(
ValueError: The 0-th circuit does not have any classical bit. Sampler requires classical bits, plus measurements on the desired qubits.
```

### What should happen?

No error.  Empty string or value of zero is appropriate for a register with no classical bits.

### Any suggestions?

Related issue: #12043

**Comment by garrison** [comment]
Actually, until more than one classical register is supported (#11967), I think this behavior is reasonable, especially since it is happening in the `base/validation.py` for primitives v1.  I am going to close this.  (I opened this issue prematurely before I fully understood what was happening.)
