### ISSUE TITLE
ImportError: DLL load failed while importing symengine_wrapper: The specified module could not be found.

### ISSUE THREAD

**Issue by josephising** [Qiskit/qiskit#12389]
### Environment

- **Qiskit version**: qiskit-1.0.2
- **Python version**: 3.12.3
- **Operating system**: Windows 10 22H2 19045.4291
Package list given by python: dill-0.3.8 mpmath-1.3.0 numpy-1.26.4 pbr-6.0.0 python-dateutil-2.9.0.post0 qiskit-1.0.2 rustworkx-0.14.2 scipy-1.13.0 six-1.16.0 stevedore-5.2.0 symengine-0.11.0 sympy-1.12 typing-extensions-4.11.0

### What is happening?

First time using qiskit, fresh install of everything
First I install python 3.12.3
Then first thing is use "pip install qiskit", it manages to download and install all packages listed above including qiskit 1.0.2
Then using IDLE or "python" in commandline to run python shell commands:
"import qiskit as qk" the following error:

`>>> import qiskit as qk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\python\AppData\Local\Programs\Python\Python312\Lib\site-packages\qiskit\__init__.py", line 78, in <module>
    from qiskit.circuit import ClassicalRegister
  File "C:\Users\python\AppData\Local\Programs\Python\Python312\Lib\site-packages\qiskit\circuit\__init__.py", line 386, in <module>
    from .quantumcircuit import QuantumCircuit
  File "C:\Users\python\AppData\Local\Programs\Python\Python312\Lib\site-packages\qiskit\circuit\quantumcircuit.py", line 40, in <module>
    from qiskit.utils.multiprocessing import is_main_process
  File "C:\Users\python\AppData\Local\Programs\Python\Python312\Lib\site-packages\qiskit\utils\__init__.py", line 67, in <module>
    from .units import apply_prefix, detach_prefix
  File "C:\Users\python\AppData\Local\Programs\Python\Python312\Lib\site-packages\qiskit\utils\units.py", line 18, in <module>
    from qiskit.circuit.parameterexpression import ParameterExpression
  File "C:\Users\python\AppData\Local\Programs\Python\Python312\Lib\site-packages\qiskit\circuit\parameterexpression.py", line 23, in <module>
    import symengine
  File "C:\Users\python\AppData\Local\Programs\Python\Python312\Lib\site-packages\symengine\__init__.py", line 12, in <module>
    import symengine.lib.symengine_wrapper as wrapper
ImportError: DLL load failed while importing symengine_wrapper: The specified module could not be found.`

### How can we reproduce the issue?

Install Python 3.12.3 in clean environment
pip install qiskit
"import qiskit as qk"

### What should happen?

What should happen if you run the above code: symengine_wrapper error message;
what should happen normally: run code as normal

**Comment by josephising** [comment]
following the tutorial on main page: https://github.com/Qiskit/qiskit?tab=readme-ov-file#create-your-first-quantum-program-in-qiskit
if instead type the line: "from qiskit import QuantumCircuit" the following error: 
>>> from qiskit import QuantumCircuit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\python\AppData\Local\Programs\Python\Python312\Lib\site-packages\qiskit\__init__.py", line 54, in <module>
    sys.modules["qiskit._accelerate.nlayout"] = qiskit._accelerate.nlayout
                                                ^^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'qiskit' has no attribute '_accelerate' (most likely due to a circular import)
>>> from qiskit import QuantumCircuit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\python\AppData\Local\Programs\Python\Python312\Lib\site-packages\qiskit\__init__.py", line 54, in <module>
    sys.modules["qiskit._accelerate.nlayout"] = qiskit._accelerate.nlayout
                                                ^^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'qiskit' has no attribute '_accelerate' (most likely due to a circular import)

**Comment by josephising** [comment]
it was fixed by downloading C++ redistributable from https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist
namely the latest x64 version (14.38.33135.0)
