### ISSUE TITLE
Scheduling pass on circuit not being recognized in time_dynamical_decoupling_pass

### ISSUE THREAD

**Issue by Procatv** [Qiskit/qiskit#12505]
### Environment

Qiskit v1.1.0
Python 3.9.6
Sonoma 14.5

### What is happening?

None of the tests in scheduling_passes are working, I know what's causing all the tests to fail except time_dynamical_decoupling_pass, no matter if I enter a circuit or dag it still fails by either saying to call one of the scheduling passes even if I already did when its a circuit and if I enter a dag it says that the list object has no attribute values

``` 
100.00%] ··· scheduling_passes.SchedulingPassBenchmarks.time_dynamical_decoupling_pass                                                                                                                                      failed
[100.00%] ··· ========== ======== ========
              --               depth      
              ---------- -----------------
               n_qubits    500      1000  
              ========== ======== ========
                  5       failed   failed 
                  10      failed   failed 
                  20      failed   failed 
              ========== ======== ========
              For parameters: 5, 500
              Traceback (most recent call last):
                File "/Users/catherinelozano/Desktop/Qiskit_work/py-qiskit/lib/python3.9/site-packages/asv/benchmark.py", line 80, in <module>
                  main()
                File "/Users/catherinelozano/Desktop/Qiskit_work/py-qiskit/lib/python3.9/site-packages/asv/benchmark.py", line 72, in main
                  commands[mode](args)
                File "/Users/catherinelozano/Desktop/Qiskit_work/qiskit-terra-catherines/.asv/env/63b4d1e2919fcd950c89910ea84c38ee/lib/python3.9/site-packages/asv_runner/run.py", line 72, in _run
                  result = benchmark.do_run()
                File "/Users/catherinelozano/Desktop/Qiskit_work/qiskit-terra-catherines/.asv/env/63b4d1e2919fcd950c89910ea84c38ee/lib/python3.9/site-packages/asv_runner/benchmarks/_base.py", line 661, in do_run
                  return self.run(*self._current_params)
                File "/Users/catherinelozano/Desktop/Qiskit_work/qiskit-terra-catherines/.asv/env/63b4d1e2919fcd950c89910ea84c38ee/lib/python3.9/site-packages/asv_runner/benchmarks/time.py", line 165, in run
                  samples, number = self.benchmark_timing(
                File "/Users/catherinelozano/Desktop/Qiskit_work/qiskit-terra-catherines/.asv/env/63b4d1e2919fcd950c89910ea84c38ee/lib/python3.9/site-packages/asv_runner/benchmarks/time.py", line 258, in benchmark_timing
                  timing = timer.timeit(number)
                File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/timeit.py", line 177, in timeit
                  timing = self.inner(it, self.timer)
                File "<timeit-src>", line 6, in inner
                File "/Users/catherinelozano/Desktop/Qiskit_work/qiskit-terra-catherines/.asv/env/63b4d1e2919fcd950c89910ea84c38ee/lib/python3.9/site-packages/asv_runner/benchmarks/time.py", line 90, in func
                  self.func(*param)
                File "/Users/catherinelozano/Desktop/Qiskit_work/qiskit-terra-catherines/test/benchmarks/scheduling_passes.py", line 155, in time_dynamical_decoupling_pass
                  PadDynamicalDecoupling(self.durations, dd_sequence=[XGate(), XGate()]).run(
                File "/Users/catherinelozano/Desktop/Qiskit_work/qiskit-terra-catherines/.asv/env/63b4d1e2919fcd950c89910ea84c38ee/lib/python3.9/site-packages/qiskit/transpiler/passes/scheduling/padding/base_padding.py", line 84, in run
                  self._pre_runhook(dag)
                File "/Users/catherinelozano/Desktop/Qiskit_work/qiskit-terra-catherines/.asv/env/63b4d1e2919fcd950c89910ea84c38ee/lib/python3.9/site-packages/qiskit/transpiler/passes/scheduling/padding/dynamical_decoupling.py", line 203, in _pre_runhook
                  super()._pre_runhook(dag)
                File "/Users/catherinelozano/Desktop/Qiskit_work/qiskit-terra-catherines/.asv/env/63b4d1e2919fcd950c89910ea84c38ee/lib/python3.9/site-packages/qiskit/transpiler/passes/scheduling/padding/base_padding.py", line 184, in _pre_runhook
                  raise TranspilerError(
              qiskit.transpiler.exceptions.TranspilerError: 'The input circuit circuit-160 is not scheduled. Call one of scheduling passes before running the PadDynamicalDecoupling pass.
 ```

### How can we reproduce the issue?

By running asv run^! —b scheduling_passes

### What should happen?

scheduling_passes should run and produce results

### Any suggestions?

The random circuit function in line 42 should have conditional=False, and reset=False since 
raise TranspilerError(ex.message) from ex
             qiskit.transpiler.exceptions.TranspilerError: 'Conditional instruction reset is not supported in ALAP scheduler.'
In line 119, 132, 142, we should be running the self.transpiled_circuit instead of the self.timed_dag) as with self.timed_dag there is a dagCircuitError: raise DAGCircuitError("not a QuantumRegister instance.")
              qiskit.dagcircuit.exceptions.DAGCircuitError: 'not a QuantumRegister instance.'

**Comment by Procatv** [comment]
Can I be assigned this issue?
