### ISSUE TITLE
Depreciation error for '+=' in ripple_adder

### ISSUE THREAD

**Issue by Procatv** [Qiskit/qiskit#12502]
### Environment

Qiskit v1.1.0
Python 3.9.6
Sonoma 14.5

### What is happening?

Attempting to run the asv benchmark suite, specifically the ripple_adder benchmark results in depreciation error from line 216 in qiskit/test/benchmarks/utils.py

```
[[16.67%] ··· Running (ripple_adder.RippleAdderConstruction.time_build_ripple_adder--)..
[66.67%] ··· ripple_adder.RippleAdderConstruction.time_build_ripple_adder                                                                                                                                                   failed
[66.67%] ··· ====== ========
              size          
             ------ --------
               10    failed 
               50    failed 
              100    failed 
              200    failed 
              500    failed 
             ====== ========
             For parameters: 10
             Traceback (most recent call last):
               File "/Users/catherinelozano/Desktop/Qiskit_work/py-qiskit/lib/python3.9/site-packages/asv/benchmark.py", line 80, in <module>
                 main()
               File "/Users/catherinelozano/Desktop/Qiskit_work/py-qiskit/lib/python3.9/site-packages/asv/benchmark.py", line 72, in main
                 commands[mode](args)
               File "/Users/catherinelozano/Desktop/Qiskit_work/qiskit-terra-catherines/.asv/env/63b4d1e2919fcd950c89910ea84c38ee/lib/python3.9/site-packages/asv_runner/run.py", line 72, in _run
                 result = benchmark.do_run()
               File "/Users/catherinelozano/Desktop/Qiskit_work/qiskit-terra-catherines/.asv/env/63b4d1e2919fcd950c89910ea84c38ee/lib/python3.9/site-packages/asv_runner/benchmarks/_base.py", line 661, in do_run
                 return self.run(*self._current_params)
               File "/Users/catherinelozano/Desktop/Qiskit_work/qiskit-terra-catherines/.asv/env/63b4d1e2919fcd950c89910ea84c38ee/lib/python3.9/site-packages/asv_runner/benchmarks/time.py", line 165, in run
                 samples, number = self.benchmark_timing(
               File "/Users/catherinelozano/Desktop/Qiskit_work/qiskit-terra-catherines/.asv/env/63b4d1e2919fcd950c89910ea84c38ee/lib/python3.9/site-packages/asv_runner/benchmarks/time.py", line 258, in benchmark_timing
                 timing = timer.timeit(number)
               File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/timeit.py", line 177, in timeit
                 timing = self.inner(it, self.timer)
               File "<timeit-src>", line 6, in inner
               File "/Users/catherinelozano/Desktop/Qiskit_work/qiskit-terra-catherines/.asv/env/63b4d1e2919fcd950c89910ea84c38ee/lib/python3.9/site-packages/asv_runner/benchmarks/time.py", line 90, in func
                 self.func(*param)
               File "/Users/catherinelozano/Desktop/Qiskit_work/qiskit-terra-catherines/test/benchmarks/ripple_adder.py", line 29, in time_build_ripple_adder
                 build_ripple_adder_circuit(size)
               File "/Users/catherinelozano/Desktop/Qiskit_work/qiskit-terra-catherines/test/benchmarks/utils.py", line 216, in build_ripple_adder_circuit
                 qc += adder_subcircuit
             TypeError: unsupported operand type(s) for +=: 'QuantumCircuit' and 'QuantumCircuit'
```

### How can we reproduce the issue?

By running asv run^! —b ripple_adder

### What should happen?

ripple_adder benchmark tests should run and produce results 

### Any suggestions?

Replacing the addition assignment operator with ‘&=‘ in qiskit/test/benchmarks/utils.py line 216 following the deprecation of extend, +, and += for class .QuantumCircuit per release notes 0.23 (qiskit/releasenotes/notes/0.23/remove-deprecated-circuit-methods-3e4eb27c4709ba12.yaml)

**Comment by Procatv** [comment]
Can I be assigned this issue?

**Comment by raynelfss** [comment]
Done!
