### ISSUE TITLE
`TranspileLayoutl.final_index_layout` breaks for a simple `TranspileLayout` instance

### ISSUE THREAD

**Issue by mrossinek** [Qiskit/qiskit#12749]
### Environment

- **Qiskit version**: main @ d86f9958516ee7f48359ddc7364050bb791602d1
- **Python version**: Any
- **Operating system**: Any

### What is happening?

The `TranspileLayout` class cannot be fully used standalone when initialized with the only two required input arguments.
More concretely, accessing `TranspileLayout.final_index_layout` produces the following error using the code below:
```
Traceback (most recent call last):
  File "/home/oss/Files/Dev/Qiskit/qiskit/main/tmp.py", line 14, in <module>
    print(qc.layout.final_index_layout())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oss/Files/Dev/Qiskit/qiskit/main/qiskit/transpiler/layout.py", line 665, in final_index_layout
    [
  File "/home/oss/Files/Dev/Qiskit/qiskit/main/qiskit/transpiler/layout.py", line 668, in <listcomp>
    if getattr(x, "_register", "").startswith("ancilla")
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QuantumRegister' object has no attribute 'startswith'
```

This originates originates from here: https://github.com/Qiskit/qiskit/blob/d86f9958516ee7f48359ddc7364050bb791602d1/qiskit/transpiler/layout.py#L668

where `_register` is tried to be used like `_name`. Simply replacing it with `_name` is not sufficient however (even though that was probably the intention and, thus, should be done), as then the next failure occurs on this line: https://github.com/Qiskit/qiskit/blob/d86f9958516ee7f48359ddc7364050bb791602d1/qiskit/transpiler/layout.py#L674

because `final_layout` is `None`, too.

### How can we reproduce the issue?

```python
from qiskit.circuit import QuantumRegister
from qiskit.transpiler.layout import Layout, TranspileLayout

qr = QuantumRegister(3)
ancillas = QuantumRegister(3, name="ancilla")
joined = list(qr) + list(ancillas)
layout = TranspileLayout(
    Layout.generate_trivial_layout(qr),
    {qubit: index for index, qubit in enumerate(joined)},
)
print(layout.final_index_layout())
```

### What should happen?

It should be possible to use all methods of the `TranspileLayout` class (which is part of the public API) when only initializing it with the required arguments.

### Any suggestions?

Replacing `_register` with `_name` is one bug fixed.

The other problem would be to guard against `self.final_layout` being `None`. The problem is, that it is not entirely clear to me, what the default value of it should be. Simply using `list(self.input_qubit_mapping.keys())` seems potentially wrong, as this depends on the order of the qubits in that mapping.

**Comment by mrossinek** [comment]
Tagging @mtreinish and linking to the possibly related https://github.com/Qiskit/qiskit/issues/10817 as per the comment here: https://github.com/Qiskit/qiskit/blob/main/qiskit/transpiler/layout.py#L662-L663

Cc @ElePT @Cryoris
