### ISSUE TITLE
Memory Error when running `tox` locally for testing

### ISSUE THREAD

**Issue by shravanpatel30** [Qiskit/qiskit#12741]
### Environment

- **Qiskit version**: 1.2.0
- **Python version**: 3.12.1
- **Operating system**: Windows 11

### What is happening?

After editing some code locally, when I try to run tests by running `tox` everthing works fine for sometime and then I am getting Memory Error and the testing throws error. I followed the directions from `CONTRIBUTING.md` document to run test on individual `test_*.py` files and it works perfectly fine. My PC has 16 GB memory so do I need more than that if I want to run tests locally? And if I don't run tests locally should I go ahead and open a pull request and let GitHub CLI do the testing? 

### How can we reproduce the issue?

Run `tox` locally in python 3.12 environment.

### What should happen?

I believe the `tox` command should not return memory error.

### Any suggestions?

Maybe there is some command to limit the memory usage when testing is done but nothing is specified in the `CONTRIBUTING.md` document.

**Comment by jakelishman** [comment]
Please can you share the traceback you are seeing?

Have you made changes that you're testing, or are you testing on `main`?

**Comment by shravanpatel30** [comment]
There were many different memory related errors. Here I am sharing a few of them and I am also attaching a file that contains the full cmd output. 

I made some changes to the PauliFeatureMap while working on fixing the issue where it won't work at all if a list of entanglement was passed. I invoked `tox` to run all the tests while I was on a branch (in my fork) which is up-to-date with the qiskit `main`.
[full_errorlog.txt](https://github.com/user-attachments/files/16152286/full_errorlog.txt)


- Error1
```
 {4} test.python.qasm2.test_parse_errors.TestIncompleteStructure.test_bad_token_0068__include__if [0.000000s] ... ok
{2} test.python.primitives.test_backend_estimator_v2.TestBackendEstimatorV2.test_estimator_with_pub_3 [0.380740s] ... FAILED

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "C:\qiskit\.tox\py312\Lib\site-packages\ddt.py", line 221, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "C:\qiskit\test\python\primitives\test_backend_estimator_v2.py", line 145, in test_estimator_with_pub
    result4 = estimator.run([pub1, pub2]).result()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "C:\qiskit\qiskit\primitives\primitive_job.py", line 51, in result
    return self._future.result()
           ^^^^^^^^^^^^^^^^^^^^^

      File "C:\Users\shrav\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^

      File "C:\Users\shrav\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception

      File "C:\Users\shrav\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "C:\qiskit\qiskit\primitives\backend_estimator_v2.py", line 171, in _run
    pub_results = self._run_pubs([pubs[i] for i in lst], shots)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "C:\qiskit\qiskit\primitives\backend_estimator_v2.py", line 186, in _run_pubs
    run_result, metadata = _run_circuits(
                           ^^^^^^^^^^^^^^

      File "C:\qiskit\qiskit\primitives\backend_estimator.py", line 72, in _run_circuits
    backend.run(circuits[pos : pos + max_circuits], **run_options)

      File "C:\qiskit\qiskit\providers\fake_provider\fake_backend.py", line 157, in run
    job = self.sim.run(circuits, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "C:\qiskit\qiskit\providers\basic_provider\basic_simulator.py", line 542, in run
    job = BasicProviderJob(self, job_id, self._run_job(job_id, qobj))
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "C:\qiskit\qiskit\providers\basic_provider\basic_simulator.py", line 562, in _run_job
    result_list.append(self.run_experiment(experiment))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

MemoryError:
      File "C:\qiskit\qiskit\providers\basic_provider\basic_simulator.py", line 761, in run_experiment
    memory = self._add_sample_measure(measure_sample_ops, self._shots)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "C:\qiskit\qiskit\providers\basic_provider\basic_simulator.py", line 352, in _add_sample_measure
    memory.append(hex(int(value, 2)))

    MemoryError
```

- Error2:
```
{3} test.python.primitives.test_backend_estimator_v2.TestBackendEstimatorV2.test_diff_precision_6 [0.648576s] ... FAILED

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "C:\qiskit\.tox\py312\Lib\site-packages\ddt.py", line 221, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "C:\qiskit\test\python\primitives\test_backend_estimator_v2.py", line 387, in test_diff_precision
    result = job.result()
             ^^^^^^^^^^^^

      File "C:\qiskit\qiskit\primitives\primitive_job.py", line 51, in result
    return self._future.result()
           ^^^^^^^^^^^^^^^^^^^^^

      File "C:\Users\shrav\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^

      File "C:\Users\shrav\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception

      File "C:\Users\shrav\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "C:\qiskit\qiskit\primitives\backend_estimator_v2.py", line 171, in _run
    pub_results = self._run_pubs([pubs[i] for i in lst], shots)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "C:\qiskit\qiskit\primitives\backend_estimator_v2.py", line 186, in _run_pubs
    run_result, metadata = _run_circuits(
                           ^^^^^^^^^^^^^^

      File "C:\qiskit\qiskit\primitives\backend_estimator.py", line 72, in _run_circuits
    backend.run(circuits[pos : pos + max_circuits], **run_options)

      File "C:\qiskit\qiskit\providers\backend_compat.py", line 449, in run
    return self._backend.run(run_input, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "C:\qiskit\qiskit\providers\fake_provider\fake_backend.py", line 157, in run
    job = self.sim.run(circuits, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "C:\qiskit\qiskit\providers\basic_provider\basic_simulator.py", line 542, in run
    job = BasicProviderJob(self, job_id, self._run_job(job_id, qobj))
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "C:\qiskit\qiskit\providers\basic_provider\basic_simulator.py", line 562, in _run_job
    result_list.append(self.run_experiment(experiment))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "C:\qiskit\qiskit\providers\basic_provider\basic_simulator.py", line 761, in run_experiment
    memory = self._add_sample_measure(measure_sample_ops, self._shots)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "C:\qiskit\qiskit\providers\basic_provider\basic_simulator.py", line 341, in _add_sample_measure
    samples = self._local_random.choice(range(2**num_measured), num_samples, p=probabilities)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "numpy\\random\\_generator.pyx", line 1007, in numpy.random._generator.Generator.choice

    numpy._core._exceptions._ArrayMemoryError: Unable to allocate 488. KiB for an array with shape (62500,) and data type int64

```
