### ISSUE TITLE
Cannot build docs: ValueError: earliest-version set to unknown revision '1.0.0rc1'

### ISSUE THREAD

**Issue by altaris** [Qiskit/qiskit#12795]
### Environment

- **Qiskit version**: `main` branch, [commit `e5ee1a8d9`](https://github.com/Qiskit/qiskit/tree/e5ee1a8d97753ccca09b0c15be7b7ab0c1c84b90)
- **Python version**: 3.11
- **Operating system**: macOS Sonoma 14.5 / Ubuntu 22.04.4

### What is happening?

Cannot build the docs. Running `tox run -edocs` produces
```
...

docs: commands[0]> sphinx-build -W -j auto -T --keep-going -b html docs/ docs/_build/html
Running Sphinx v7.1.2
[autosummary] generating autosummary for: apidoc/assembler.rst, apidoc/circuit.rst, apidoc/circuit_classical.rst, apidoc/circuit_library.rst, apidoc/circuit_singleton.rst, apidoc/classicalfunction.rst, apidoc/compiler.rst, apidoc/converters.rst, apidoc/dagcircuit.rst, apidoc/exceptions.rst, ..., stubs/qiskit.visualization.plot_distribution.rst, stubs/qiskit.visualization.plot_error_map.rst, stubs/qiskit.visualization.plot_gate_map.rst, stubs/qiskit.visualization.plot_histogram.rst, stubs/qiskit.visualization.plot_state_city.rst, stubs/qiskit.visualization.plot_state_hinton.rst, stubs/qiskit.visualization.plot_state_paulivec.rst, stubs/qiskit.visualization.plot_state_qsphere.rst, stubs/qiskit.visualization.timeline_drawer.rst, stubs/qiskit.visualization.visualize_transition.rst
loading intersphinx inventory from https://www.rustworkx.org/objects.inv...
loading intersphinx inventory from https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/objects.inv...
loading intersphinx inventory from https://qiskit.github.io/qiskit-aer/objects.inv...
loading intersphinx inventory from https://numpy.org/doc/stable/objects.inv...
loading intersphinx inventory from https://matplotlib.org/stable/objects.inv...
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 512 source files that are out of date
updating environment: [new config] 512 added, 0 changed, 0 removed
reading sources... [ 17%] stubs/qiskit.circuit.library.CDKMRippleCarryAdder .. stubs/qiskit.circuit.library.EfficientS
reading sources... [ 21%] stubs/qiskit.circuit.library.EvolvedOperatorAnsatz .. stubs/qiskit.circuit.library.IntegerCo
reading sources... [ 33%] stubs/qiskit.circuit.library.RealAmplitudes .. stubs/qiskit.circuit.library.VBERippleCarryAd
reading sources... [ 75%] stubs/qiskit.transpiler.TransformationPass .. stubs/qiskit.transpiler.passes.CommutativeCancscanning /Users/cedric/repositories/qiskit/releasenotes/notes for current branch release notes

(Error in parallel process)
Traceback (most recent call last):
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/sphinx/util/parallel.py", line 73, in _process
    ret = func(arg)
          ^^^^^^^^^
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 456, in read_process
    self.read_doc(docname, _cache=False)
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 494, in read_doc
    publisher.publish()
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/docutils/core.py", line 234, in publish
    self.document = self.reader.read(self.source, self.parser,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/sphinx/io.py", line 104, in read
    self.parse()
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/docutils/readers/__init__.py", line 76, in parse
    self.parser.parse(self.input, document)
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/sphinx/parsers.py", line 80, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 169, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
                                  ^^^^^^^^^^^^^^^^
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 3024, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 325, in section
    self.new_subsection(title, lineno, messages)
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 391, in new_subsection
    newabsoffset = self.nested_parse(
                   ^^^^^^^^^^^^^^^^^^
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
                                  ^^^^^^^^^^^^^^^^
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2357, in explicit_markup
    self.explicit_list(blank_finish)
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2382, in explicit_list
    newline_offset, blank_finish = self.nested_list_parse(
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 316, in nested_list_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
                                  ^^^^^^^^^^^^^^^^
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2660, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2367, in explicit_construct
    return method(self, expmatch)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2104, in directive
    return self.run_directive(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2154, in run_directive
    result = directive_instance.run()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/reno/sphinxext.py", line 114, in run
    with loader.Loader(conf) as ldr:
         ^^^^^^^^^^^^^^^^^^^
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/reno/loader.py", line 62, in __init__
    self._load_data()
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/reno/loader.py", line 90, in _load_data
    self._scanner_output = self._scanner.get_notes_by_version()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cedric/repositories/qiskit/.tox/docs/lib/python3.11/site-packages/reno/scanner.py", line 1005, in get_notes_by_version
    raise ValueError(
ValueError: earliest-version set to unknown revision '1.0.0rc1'

Sphinx parallel build error:
ValueError: earliest-version set to unknown revision '1.0.0rc1'
reading sources... [ 79%] stubs/qiskit.transpiler.passes.CommutativeInverseCancellation .. stubs/qiskit.transpiler.pasdocs: exit 2 (17.32 seconds) /Users/cedric/repositories/qiskit> sphinx-build -W -j auto -T --keep-going -b html docs/ docs/_build/html pid=67076
  docs: FAIL code 2 (73.06=setup[54.13]+cmd[1.61,17.32] seconds)
  evaluation failed :( (73.14 seconds)
```

### How can we reproduce the issue?

Running `tox run -edocs`.

### What should happen?

The docs should be built with no errors.

**Comment by jakelishman** [comment]
You'll need to fetch the git tags, which you can do with `git fetch --tags upstream`, where `upstream` is whatever name you gave `Qiskit/qiskit`.  If you get subsequent errors about `stable/0.46`, `stable/1.0` or `stable/1.1`, you'll just need to ensure that those branches are created locally, which you can do with `git checkout stable/0.46` (etc), and then use `git checkout` to go back to whichever branch you wanted.

**Comment by altaris** [comment]
Thanks, that fixed it!
