### ISSUE TITLE
`qasm2.dumps` fails to export `Initialize` and `PrepareState` with array inputs

### ISSUE THREAD

**Issue by Strke** [Qiskit/qiskit#12879]
### Environment

* Qiskit Terra version: 0.43.1 meta package, terra 0.24.1
* Python version: 3.10
* Operating system: docker continuumio/miniconda

### What is happening?

function `QuantumCircuit().from_qasm_str()` unable to convert string to OpenQASM

### How can we reproduce the issue?

Run the python script
```python
from qiskit import QuantumCircuit
from qiskit.compiler import transpile

# Create a circuit with 2 qubits
circuit = QuantumCircuit(2)

# Define a state vector
state_vector = [0, 1, 0, 0]

# Fold the state into the circuit
circuit.initialize(state_vector, [0, 1])

# get any the global variables (including the circuits)
global_vars = list(globals().keys())
# keep all those that are QuantumCircuit
circuits = [
    globals()[var] for var in global_vars
    if isinstance(globals()[var], QuantumCircuit)
]
for circuit in circuits:
    for lvl in range(0, 4):
        res = transpile(circuit, optimization_level=lvl)
            # print(f"Optimization level {lvl} for circuit {circuit.name}")
            # print(res.draw())

    # conert them to qasm and back
for circuit in circuits:
        # print(f"Converting to qasm and back for circuit {circuit.name}")
    QuantumCircuit().from_qasm_str(circuit.qasm())
```
and get the error
```
Traceback (most recent call last):
  File "***/1.py", line 29, in <module>
    QuantumCircuit().from_qasm_str(circuit.qasm())
  File "/root/anaconda3/envs/fuzz4all/lib/python3.10/site-packages/qiskit/circuit/quantumcircuit.py", line 2529, in from_qasm_str
    return _circuit_from_qasm(qasm)
  File "/root/anaconda3/envs/fuzz4all/lib/python3.10/site-packages/qiskit/circuit/quantumcircuit.py", line 4964, in _circuit_from_qasm
    ast = qasm.parse()
  File "/root/anaconda3/envs/fuzz4all/lib/python3.10/site-packages/qiskit/qasm/qasm.py", line 53, in parse
    return qasm_p.parse(self._data)
  File "/root/anaconda3/envs/fuzz4all/lib/python3.10/site-packages/qiskit/qasm/qasmparser.py", line 1137, in parse
    self.parser.parse(data, lexer=self.lexer, debug=self.parse_deb)
  File "/root/anaconda3/envs/fuzz4all/lib/python3.10/site-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/root/anaconda3/envs/fuzz4all/lib/python3.10/site-packages/ply/yacc.py", line 1120, in parseopt_notrack
    p.callable(pslice)
  File "/root/anaconda3/envs/fuzz4all/lib/python3.10/site-packages/qiskit/qasm/qasmparser.py", line 397, in p_id_e
    raise QasmError("Expected an ID, received '" + str(program[1].value) + "'")
qiskit.qasm.exceptions.QasmError: "Expected an ID, received 'reset'"
```

### What should happen?

Run successfully.

**Comment by jakelishman** [comment]
This is an old and unsupported version of Qiskit.  The latest versions will show a different error with this, which is showing an actual bug that still remains:

```python
from qiskit import QuantumCircuit, qasm2

qc = QuantumCircuit(2)
qc.initialize([0, 1, 0, 0], [0, 1])
qasm2.dumps(qc)
```
```text
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[22], line 5
      3 qc = QuantumCircuit(2)
      4 qc.initialize([0, 1, 0, 0], [0, 1])
----> 5 qasm2.dumps(qc)

File ~/code/qiskit/terra/qiskit/qasm2/export.py:185, in dumps(circuit)
    183         instruction_qasm = "barrier;" if not qargs else f"barrier {qargs};"
    184     else:
--> 185         instruction_qasm = _custom_operation_statement(instruction, gates_to_define, bit_labels)
    186     instruction_calls.append(instruction_qasm)
    187 instructions_qasm = "\n".join(f"{call}" for call in instruction_calls)

[... cut ...]

File ~/code/qiskit/terra/qiskit/qasm2/export.py:247, in <listcomp>(.0)
    245     qasm2_call = operation.name
    246 if operation.params:
--> 247     params = ",".join([pi_check(i, output="qasm", eps=1e-12) for i in operation.params])
    248     qasm2_call = f"{qasm2_call}({params})"
    249 if operation.condition is not None:

File ~/code/qiskit/terra/qiskit/circuit/tools/pi_check.py:176, in pi_check(inpt, eps, output, ndigits)
    173         return f"{single_inpt:#}" if ndigits is None else f"{single_inpt:#.{ndigits}g}"
    174     return f"{single_inpt}" if ndigits is None else f"{single_inpt:.{ndigits}g}"
--> 176 complex_inpt = complex(inpt)
    177 real, imag = map(normalize, [complex_inpt.real, complex_inpt.imag])
    179 jstr = "\\jmath" if output == "latex" else "j"

TypeError: only length-1 arrays can be converted to Python scalars
```

The problem is that we're trying to treat some things as parameters that wouldn't be valid OpenQASM 2 (in this case a Numpy array) - the old version of the code just silently ignored it, and generated an invalid OpenQASM 2 file, whereas we now at least fail to generate it.
