### ISSUE TITLE
Transpile error when transpile the circuit

### ISSUE THREAD

**Issue by Strke** [Qiskit/qiskit#12880]
### Environment

* Qiskit Terra version: 0.43.1 meta package, terra 0.24.1
* Python version: 3.10
* Operating system: docker continuumio/miniconda

### What is happening?

The gate add to the circuit and cause the circuit transpile error

### How can we reproduce the issue?

Run the code 
```python 
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister, execute, Aer
from qiskit.circuit import Gate
from qiskit.extensions import HGate, XGate
from qiskit.compiler import transpile

# Create a Quantum Register with 4 qubits.
qr = QuantumRegister(4)
# Create a Classical Register with 4 bits.
cr = ClassicalRegister(4)
# Create a Quantum Circuit acting on the qr register
circuit = QuantumCircuit(qr, cr)

# Add a H gate on qubit 0, and a X gate on qubit 1
circuit.x(1)
circuit.h(0)

# Add a custom gate to the circuit
hx_gate = Gate(name='HX', num_qubits=2, params=[])
hx_gate.definition = [(HGate(), [0]), (XGate(), [1])]
circuit.append(hx_gate, [0, 1])

# Add a H gate on qubit 2, and a X gate on qubit 3
circuit.h(2)
circuit.x(3)

# Add a custom gate to the circuit
hx_gate = Gate(name='HX', num_qubits=2, params=[])
hx_gate.definition = [(HGate(), [0]), (XGate(), [1])]
circuit.append(hx_gate, [2, 3])

# Measure all qubits
circuit.measure_all()

# Draw the circuit
print(circuit.draw())

# get any the global variables (including the circuits)
global_vars = list(globals().keys())
# keep all those that are QuantumCircuit
circuits = [
    globals()[var] for var in global_vars
    if isinstance(globals()[var], QuantumCircuit)
]
    # transpile them
for circuit in circuits:
     for lvl in range(0, 4):
         res = transpile(circuit, optimization_level=lvl)
         # print(f"Optimization level {lvl} for circuit {circuit.name}")
         # print(res.draw())

    # conert them to qasm and back
for circuit in circuits:
    # print(f"Converting to qasm and back for circuit {circuit.name}")
    QuantumCircuit().from_qasm_str(circuit.qasm())
```
and get the error
```
        ┌───┐┌─────┐ ░ ┌─┐         
  q0_0: ┤ H ├┤0    ├─░─┤M├─────────
        ├───┤│  HX │ ░ └╥┘┌─┐      
  q0_1: ┤ X ├┤1    ├─░──╫─┤M├──────
        ├───┤├─────┤ ░  ║ └╥┘┌─┐   
  q0_2: ┤ H ├┤0    ├─░──╫──╫─┤M├───
        ├───┤│  HX │ ░  ║  ║ └╥┘┌─┐
  q0_3: ┤ X ├┤1    ├─░──╫──╫──╫─┤M├
        └───┘└─────┘ ░  ║  ║  ║ └╥┘
  c0: 4/════════════════╬══╬══╬══╬═
                        ║  ║  ║  ║ 
meas: 4/════════════════╩══╩══╩══╩═
                        0  1  2  3 
Traceback (most recent call last):
  File "/home/Fuzz4All/outputs/full_run/qiskit-myfuzz/bug/1.fuzz", line 48, in <module>
    res = transpile(circuit, optimization_level=lvl)
  File "/root/anaconda3/envs/fuzz4all/lib/python3.10/site-packages/qiskit/compiler/transpiler.py", line 380, in transpile
    _serial_transpile_circuit(
  File "/root/anaconda3/envs/fuzz4all/lib/python3.10/site-packages/qiskit/compiler/transpiler.py", line 462, in _serial_transpile_circuit
    result = pass_manager.run(circuit, callback=callback, output_name=output_name)
  File "/root/anaconda3/envs/fuzz4all/lib/python3.10/site-packages/qiskit/transpiler/passmanager.py", line 537, in run
    return super().run(circuits, output_name, callback)
  File "/root/anaconda3/envs/fuzz4all/lib/python3.10/site-packages/qiskit/transpiler/passmanager.py", line 231, in run
    return self._run_single_circuit(circuits, output_name, callback)
  File "/root/anaconda3/envs/fuzz4all/lib/python3.10/site-packages/qiskit/transpiler/passmanager.py", line 292, in _run_single_circuit
    result = running_passmanager.run(circuit, output_name=output_name, callback=callback)
  File "/root/anaconda3/envs/fuzz4all/lib/python3.10/site-packages/qiskit/transpiler/runningpassmanager.py", line 125, in run
    dag = self._do_pass(pass_, dag, passset.options)
  File "/root/anaconda3/envs/fuzz4all/lib/python3.10/site-packages/qiskit/transpiler/runningpassmanager.py", line 169, in _do_pass
    dag = self._do_pass(required_pass, dag, options)
  File "/root/anaconda3/envs/fuzz4all/lib/python3.10/site-packages/qiskit/transpiler/runningpassmanager.py", line 173, in _do_pass
    dag = self._run_this_pass(pass_, dag)
  File "/root/anaconda3/envs/fuzz4all/lib/python3.10/site-packages/qiskit/transpiler/runningpassmanager.py", line 227, in _run_this_pass
    pass_.run(FencedDAGCircuit(dag))
  File "/root/anaconda3/envs/fuzz4all/lib/python3.10/site-packages/qiskit/transpiler/passes/optimization/commutation_analysis.py", line 75, in run
    does_commute = self.comm_checker.commute(
  File "/root/anaconda3/envs/fuzz4all/lib/python3.10/site-packages/qiskit/circuit/commutation_checker.py", line 135, in commute
    operator_1 = Operator(op1, input_dims=(2,) * len(qarg1), output_dims=(2,) * len(qarg1))
  File "/root/anaconda3/envs/fuzz4all/lib/python3.10/site-packages/qiskit/quantum_info/operators/operator.py", line 85, in __init__
    self._data = self._init_instruction(data).data
  File "/root/anaconda3/envs/fuzz4all/lib/python3.10/site-packages/qiskit/quantum_info/operators/operator.py", line 614, in _init_instruction
    op._append_instruction(instruction)
  File "/root/anaconda3/envs/fuzz4all/lib/python3.10/site-packages/qiskit/quantum_info/operators/operator.py", line 660, in _append_instruction
    raise QiskitError(
qiskit.exceptions.QiskitError: 'Operation "HX" definition is <class \'list\'> but expected QuantumCircuit.'
```

### What should happen?

May be it should transpile successfully.

**Comment by jakelishman** [comment]
This is an old and unsupported version of Qiskit (the current is 1.1), but the immediate problem is that `gate.definition` needs to be a `QuantumCircuit`, not a list.

You can read more about the correct way to define a custom instruction/gate here: https://docs.quantum.ibm.com/api/qiskit/circuit#creating-custom-instructions.

**Comment by Strke** [comment]
OK, thanks for your reply
