### ISSUE TITLE
Importing BackendV2 results in a deprecation warning of `qiskit.providers.models`

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit#12902]
### Environment

- **Qiskit version**: main, 1.2.0rc1
- **Python version**: 3.12.4
- **Operating system**: macOS 14.6

### What is happening?

Even if I imported only BackendV2, qiskit raises a deprecation warning of `qiskit.providers.models`, which is related to BackendV1, I guess.

### How can we reproduce the issue?

```python
# test.py
from qiskit.providers.backend import BackendV2
```

```
$ python -W error::DeprecationWarning test.py
Traceback (most recent call last):
  File "/Users/ima/tasks/4_2024/qiskit/terra/tmp/test.py", line 1, in <module>
    from qiskit.providers.backend import BackendV2
  File "/Users/ima/envs/qiskit312/lib/python3.12/site-packages/qiskit/__init__.py", line 91, in <module>
    from qiskit.circuit import ClassicalRegister
  File "/Users/ima/envs/qiskit312/lib/python3.12/site-packages/qiskit/circuit/__init__.py", line 1237, in <module>
    from . import library
  File "/Users/ima/envs/qiskit312/lib/python3.12/site-packages/qiskit/circuit/library/__init__.py", line 495, in <module>
    from .generalized_gates import (
  File "/Users/ima/envs/qiskit312/lib/python3.12/site-packages/qiskit/circuit/library/generalized_gates/__init__.py", line 22, in <module>
    from .linear_function import LinearFunction
  File "/Users/ima/envs/qiskit312/lib/python3.12/site-packages/qiskit/circuit/library/generalized_gates/linear_function.py", line 22, in <module>
    from qiskit.quantum_info import Clifford
  File "/Users/ima/envs/qiskit312/lib/python3.12/site-packages/qiskit/quantum_info/__init__.py", line 116, in <module>
    from .analysis import hellinger_distance, hellinger_fidelity, Z2Symmetries
  File "/Users/ima/envs/qiskit312/lib/python3.12/site-packages/qiskit/quantum_info/analysis/__init__.py", line 17, in <module>
    from .z2_symmetries import Z2Symmetries
  File "/Users/ima/envs/qiskit312/lib/python3.12/site-packages/qiskit/quantum_info/analysis/z2_symmetries.py", line 26, in <module>
    from ..operators import Pauli, SparsePauliOp
  File "/Users/ima/envs/qiskit312/lib/python3.12/site-packages/qiskit/quantum_info/operators/__init__.py", line 18, in <module>
    from .measures import average_gate_fidelity, diamond_norm, gate_error, process_fidelity
  File "/Users/ima/envs/qiskit312/lib/python3.12/site-packages/qiskit/quantum_info/operators/measures.py", line 27, in <module>
    from qiskit.quantum_info.states.densitymatrix import DensityMatrix
  File "/Users/ima/envs/qiskit312/lib/python3.12/site-packages/qiskit/quantum_info/states/__init__.py", line 16, in <module>
    from .statevector import Statevector
  File "/Users/ima/envs/qiskit312/lib/python3.12/site-packages/qiskit/quantum_info/states/statevector.py", line 28, in <module>
    from qiskit.quantum_info.states.quantum_state import QuantumState
  File "/Users/ima/envs/qiskit312/lib/python3.12/site-packages/qiskit/quantum_info/states/quantum_state.py", line 27, in <module>
    from qiskit.result.counts import Counts
  File "/Users/ima/envs/qiskit312/lib/python3.12/site-packages/qiskit/result/__init__.py", line 62, in <module>
    from .result import Result
  File "/Users/ima/envs/qiskit312/lib/python3.12/site-packages/qiskit/result/result.py", line 19, in <module>
    from qiskit.pulse.schedule import Schedule
  File "/Users/ima/envs/qiskit312/lib/python3.12/site-packages/qiskit/pulse/__init__.py", line 65, in <module>
    from qiskit.pulse.builder import (
  File "/Users/ima/envs/qiskit312/lib/python3.12/site-packages/qiskit/pulse/builder.py", line 427, in <module>
    from qiskit.pulse import (
  File "/Users/ima/envs/qiskit312/lib/python3.12/site-packages/qiskit/pulse/macros.py", line 22, in <module>
    from qiskit.providers.backend import BackendV2
  File "/Users/ima/envs/qiskit312/lib/python3.12/site-packages/qiskit/providers/__init__.py", line 786, in <module>
    from qiskit.providers.backend import Backend
  File "/Users/ima/envs/qiskit312/lib/python3.12/site-packages/qiskit/providers/backend.py", line 24, in <module>
    from qiskit.providers.models.backendstatus import BackendStatus
  File "/Users/ima/envs/qiskit312/lib/python3.12/site-packages/qiskit/providers/models/__init__.py", line 56, in <module>
    warnings.warn(
DeprecationWarning: qiskit.providers.models is deprecated since Qiskit 1.2 and will be removed in Qiskit 2.0.With the removal of Qobj, there is no need for these schema-conformant objects. If you still needto use them, it could be because you are using a BackendV1, which is also deprecated in favorof BackendV2
```

### What should happen?

It might be nice perhaps to suppress the deprecation warning related to BackendV1 in this case.

**Comment by jlapeyre** [comment]
I do not see this bug with main 1fdd527f on fedora linux. The import succeeds silently. I have no Qiskit env variables set.
