### ISSUE TITLE
Circuit.append(Barrier, qargs=None) leaves invalid circuit.data

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit#5819]
### Information

- **Qiskit Terra version**: master @ 9d1d6a1e
- **Python version**: 3.6
- **Operating system**: osx

### What is the current behavior?

```
>>> import qiskit as qk
>>> from qiskit.circuit import Barrier
>>> qc = qk.QuantumCircuit(3)
>>> qc.x(0)
>>> qc.append(Barrier(3))
>>> qc.x(0)
>>> qc.depth()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/circuit/quantumcircuit.py", line 1437, in depth
    max_level = max(levels)
ValueError: max() arg is an empty sequence
>>> qc.data[1]
(<qiskit.circuit.barrier.Barrier object at 0x10ef6bf98>, [], [])
```
(Both `qargs` and `cargs` are `[]`.)

### What is the expected behavior?

Seems like the right behavior here is to broadcast to all qubits if `barrier.num_qubits`  == `circuit.num_qubits` (similar to what's done for `circuit.barrier())`, but if not, we should at least raise an error as we would for other instructions

```
>>> qc.append(XGate())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/circuit/quantumcircuit.py", line 932, in append
    for (qarg, carg) in instruction.broadcast_arguments(expanded_qargs, expanded_cargs):
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/circuit/gate.py", linron.')
qiskit.circuit.exceptions.CircuitError: 'The amount of qubit/clbit arguments does not match the gate expectation.'
```

**Comment by MR-Asif12116135** [comment]
I am interested to work on that.

**Comment by Cryoris** [comment]
Doesn't `append` require to provide the qargs? To not provide them, `compose` should be used. So I think this should raise an error if no qargs are specified 🙂

**Comment by kdk** [comment]
> Doesn't `append` require to provide the qargs? To not provide them, `compose` should be used. So I think this should raise an error if no qargs are specified 🙂

Surprisingly not, though maybe this is the bug. If `qargs is None`, it defaults to `[]` which will eventually raise an error from `Instruction.broadcast_arguments` for most instructions, but not `Barrier` (because it supports `qc.barrier()` with no `qargs`).

**Comment by Raghav-Bell** [comment]
hi @Cryoris 
It seems `_append()` is already going to deprecated. Can we close this issue?
https://github.com/Qiskit/qiskit/blob/96ebf2ad0902739a584f08bcafb917af85e3bf72/qiskit/circuit/quantumcircuit.py#L2393-L2406

**Comment by Cryoris** [comment]
The public `append` function is not going to be deprecated, but the issue no longer persists as doing
```python
qc.append(Barrier(3))  
```
does now raise an error since the number of qubits does not match. Thanks for pinging this issue!
