### ISSUE TITLE
Gradient with a parameterized operator raises an error

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit#6888]
### Information

- **Qiskit Terra version**: both latest and #6847
- **Python version**: 3.8.11
- **Operating system**: macOS 11.4

### What is the current behavior?

`Gradient.convert` raises an error with an operator with parameters.

### Steps to reproduce the problem

I tried the following code with main branch and #6847, but both raise an error.

```python
from qiskit.opflow import Z, X, I, StateFn, CircuitStateFn
from qiskit.opflow.gradients import Gradient
from qiskit.circuit import QuantumCircuit, QuantumRegister, Parameter

q = QuantumRegister(1)
qc = QuantumCircuit(q)
qc.h(q)
a = Parameter('a')
H = a * Z
op = ~StateFn(H) @ CircuitStateFn(primitive=qc, coeff=1.)
print('Hamiltonian', op)

params = [a]
grad = Gradient().convert(operator = op, params = params)
print('Gradient circuits', grad)

value_dict = {a: 1}
grad_result = grad.assign_parameters(value_dict).eval()
print('Gradient', grad_result)
```

output
```
Hamiltonian ComposedOp([
  OperatorMeasurement(1.0*conjugate(a) * Z),
  CircuitStateFn(
        ┌───┐
  q0_0: ┤ H ├
        └───┘
  )
])
Gradient circuits ListOp([
  1.0*Derivative(conjugate(a), a) * ComposedOp([
    OperatorMeasurement(1.0 * Z),
    CircuitStateFn(
          ┌───┐
    q0_0: ┤ H ├
          └───┘
    )
  ])
])
Traceback (most recent call last):
  File "grad.py", line 18, in <module>
    grad_result = grad.assign_parameters(value_dict).eval()
  File "/Users/ima/tasks/1_2021/qiskit/terra/qiskit/opflow/list_ops/list_op.py", line 527, in assign_parameters
    return self.traverse(lambda x: x.assign_parameters(param_dict), coeff=param_value)
  File "/Users/ima/tasks/1_2021/qiskit/terra/qiskit/opflow/list_ops/list_op.py", line 235, in traverse
    return ListOp([convert_fn(op) for op in self.oplist], **self._state(coeff=coeff))
  File "/Users/ima/tasks/1_2021/qiskit/terra/qiskit/opflow/list_ops/list_op.py", line 235, in <listcomp>
    return ListOp([convert_fn(op) for op in self.oplist], **self._state(coeff=coeff))
  File "/Users/ima/tasks/1_2021/qiskit/terra/qiskit/opflow/list_ops/list_op.py", line 527, in <lambda>
    return self.traverse(lambda x: x.assign_parameters(param_dict), coeff=param_value)
  File "/Users/ima/tasks/1_2021/qiskit/terra/qiskit/opflow/list_ops/list_op.py", line 526, in assign_parameters
    param_value = float(self.coeff.bind(binds))
  File "/Users/ima/tasks/1_2021/qiskit/terra/qiskit/circuit/parameterexpression.py", line 428, in __float__
    return float(self._symbol_expr)
  File "symengine_wrapper.pyx", line 1133, in symengine.lib.symengine_wrapper.Basic.__float__
  File "symengine_wrapper.pyx", line 958, in symengine.lib.symengine_wrapper.Basic.n
  File "symengine_wrapper.pyx", line 4194, in symengine.lib.symengine_wrapper.evalf
RuntimeError: Not Implemented
```

### What is the expected behavior?

Does `Gradient` support parameterized operators? If not, it might be good to raise an error when `Gradient.convert` detects the input operator contains `Parameter`.

**Comment by Cryoris** [comment]
Hm I think this is a problem with symengine thinking (correctly) that `a` might be complex. If you change the code to this it should work:
```
op = StateFn(H, is_measurement=True) @ CircuitStateFn(primitive=qc, coeff=1.)
```
Like that, the parameter `a` is not conjugated and that should be ok for symengine.

But this is still a bug that we should fix.

**Comment by t-imamichi** [comment]
I close this because opflow has been removed already
