### ISSUE TITLE
BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

### ISSUE THREAD

**Issue by PetarJurcevic** [Qiskit/qiskit#6973]
### Information

- **Qiskit Terra version**: 0.18.0
- **Python version**: 3.6.12
- **Operating system**: Linux, release='3.10.0-1160.36.2.el7.x86_64',

### What is the current behavior?

When I apply the full A-matrix filter to a result object I get the following error 
```Exception in thread Thread-9:
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/concurrent/futures/process.py", line 295, in _queue_management_worker
    shutdown_worker()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/concurrent/futures/process.py", line 253, in shutdown_worker
    call_queue.put_nowait(None)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/multiprocessing/queues.py", line 129, in put_nowait
    return self.put(obj, False)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/multiprocessing/queues.py", line 83, in put
    raise Full
queue.Full

---------------------------------------------------------------------------
BrokenProcessPool                         Traceback (most recent call last)
<ipython-input-81-dc6a4842e410> in <module>
----> 1 correct_qv_results_rejected = measurement_correction.filter.apply(result3, method = 'least_squares')

~/.virtualenvs/controller/lib/python3.6/site-packages/qiskit/ignis/mitigation/measurement/filters.py in apply(self, raw_data, method)
    150                 self._apply_correction,
    151                 [resultidx for resultidx, _ in enumerate(raw_data.results)],
--> 152                 task_args=(raw_data, method))
    153 
    154             for resultidx, new_counts in new_counts_list:

~/.virtualenvs/controller/lib/python3.6/site-packages/qiskit/tools/parallel.py in parallel_map(task, values, task_args, task_kwargs, num_processes)
    162             # Otherwise just reset parallel flag and error
    163             os.environ["QISKIT_IN_PARALLEL"] = "FALSE"
--> 164             raise error
    165 
    166         Publisher().publish("terra.parallel.finish")

~/.virtualenvs/controller/lib/python3.6/site-packages/qiskit/tools/parallel.py in parallel_map(task, values, task_args, task_kwargs, num_processes)
    152                 future = executor.map(_task_wrapper, param)
    153 
--> 154             results = list(future)
    155             Publisher().publish("terra.parallel.done", len(results))
    156 

/opt/rh/rh-python36/root/usr/lib64/python3.6/concurrent/futures/process.py in _chain_from_iterable_of_lists(iterable)
    364     careful not to keep references to yielded objects.
    365     """
--> 366     for element in iterable:
    367         element.reverse()
    368         while element:

/opt/rh/rh-python36/root/usr/lib64/python3.6/concurrent/futures/_base.py in result_iterator()
    584                     # Careful not to keep a reference to the popped future
    585                     if timeout is None:
--> 586                         yield fs.pop().result()
    587                     else:
    588                         yield fs.pop().result(end_time - time.monotonic())

/opt/rh/rh-python36/root/usr/lib64/python3.6/concurrent/futures/_base.py in result(self, timeout)
    423                 raise CancelledError()
    424             elif self._state == FINISHED:
--> 425                 return self.__get_result()
    426 
    427             self._condition.wait(timeout)

/opt/rh/rh-python36/root/usr/lib64/python3.6/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

### Steps to reproduce the problem
only with my notebook possible 

### Suggested solutions
??

**Comment by rsln-s** [comment]
@PetarJurcevic try updating your Python version to 3.7+. Doing so may give you a more meaningful error. See more details here:
https://stackoverflow.com/a/51006877/5675178

My guess is that you're running out of memory. Try watching the memory usage (e.g. using `htop`) before the code crashes.

**Comment by ogrisel** [comment]
@PetarJurcevic could you please try again on a recent Python version (e.g. 3.9 or 3.10)? `concurrent.futures.ProcessPoolExecutor` should be much more robust to this family of issues.

If it's still there, please provide a reproducible code snippet to allow us to investigate the cause of the problem.

**Comment by jakelishman** [comment]
Closing as likely stale.
