### ISSUE TITLE
No error is returned when `num_qubits` is `None` when instantiating circuits in the circuit libray

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit#7306]
### Environment

- **Qiskit Terra version**: 0.18.3
- **Python version**: 3.8.10
- **Operating system**: Linux (IBM Quantum Lab)

### What is happening?

No error is returned when `num_qubits` is `None` when instantiating circuits in the circuit library.

### How can we reproduce the issue?

```python
from qiskit.circuit.library import TwoLocal
qc = TwoLocal(rotation_blocks=['h', 'rx'], entanglement_blocks=['cx'])
qc.data()
```
returns an empty list indicating that qc is an empty circuit.

### What should happen?

I think there should be an error or warning when the `num_qubits` is not set (default to `None`), similar to it is set to `0` or a negative value.

```python
from qiskit.circuit.library import TwoLocal
qc = TwoLocal(num_qubits=0, rotation_blocks=['h', 'rx'], entanglement_blocks=['cx'])
```
returns `CircuitError`
```python
Traceback (most recent call last):
  File "/tmp/ipykernel_136/839332071.py", line 3, in <module>
    qc = TwoLocal(num_qubits=0, rotation_blocks=['h', 'rx'], entanglement_blocks=['cx'])
  File "/opt/conda/lib/python3.8/site-packages/qiskit/circuit/library/n_local/two_local.py", line 202, in __init__
    super().__init__(
  File "/opt/conda/lib/python3.8/site-packages/qiskit/circuit/library/n_local/n_local.py", line 147, in __init__
    self.num_qubits = num_qubits
  File "/opt/conda/lib/python3.8/site-packages/qiskit/circuit/library/n_local/n_local.py", line 181, in num_qubits
    self.qregs = [QuantumRegister(num_qubits, name="q")]
  File "/opt/conda/lib/python3.8/site-packages/qiskit/circuit/register.py", line 86, in __init__
    raise CircuitError(
CircuitError: "Register size must be positive (int '0' was provided)"
```

**Comment by HuangJunye** [comment]
This applies to many circuits in the circuit libray: `TwoLocal`, `NLocal`, `EfficientSU2`, etc. where `num_qubits` is an optional parameter. Is this behavior intended?

**Comment by HuangJunye** [comment]
After some thoughts, this might be an intended behavior. For example, we might want to specify only the general structures of the ansatz and pass to VQE. And then it’s up to the VQE algorithm to decide how many qubits are needed depending on the molecule and mapper.

Any comments? @ajavadia @Cryoris

**Comment by Cryoris** [comment]
As you said it's intended that you can define the circuit without num qubits so that it can be set later in the algo flow. However it's weird that it just builds an empty circuit if asked for it, I agree. We can add a check in the `check_configuration` method that ensures a number of qubits is given before the circuit is built.

**Comment by HuangJunye** [comment]
Sounds good to me!

The error was found by many participants during the quantum challenge. The reason is that I included the following code for setting `initial_point` before passing to VQE algorithm. (similar to this tutorial: https://qiskit.org/documentation/nature/tutorials/07_leveraging_qiskit_runtime.html#VQE)

```python
initial_point = np.random.random(ansatz.num_parameters)
```

If is very common to set initial point for VQE? In that case we lose the benefits of not setting the number of qubits for ansatz since we need to specify the number of qubits to know the number of parameters for generating initial point.

**Comment by Cryoris** [comment]
We mainly need the feature of setting the number of qubits later in the application workflow. There, the initial point is usually also determined by the application, so it's not going to be set by the user.

**Comment by jakelishman** [comment]
Closing as stale, because:
1. all the `BlueprintCircuit`s are deprecated
2. not setting `num_qubits` is the same as setting `num_qubits=0` now, and that _does_ succeed

It's kind of weird behaviour, but we're unlikely to change it at this point.
