### ISSUE TITLE
Tests use random data without seeding

### ISSUE THREAD

**Issue by jakelishman** [Qiskit/qiskit#7316]
### Environment

- **Qiskit Terra version**: 0.19.dev @ b74089e26
- **Python version**: any
- **Operating system**: any

### What is happening?

We have quite a few tests that generate randomised data, without fixing a seed first.  This means very occasionally, the test suite can fail on unrelated PRs, if we get unlucky with tolerances.

### How can we reproduce the issue?

For example, [this recent CI run had a failure in `test_isometry_tolerance`](https://dev.azure.com/qiskit-ci/qiskit-terra/_build/results?buildId=32903&view=logs&j=8fcf860c-8d5a-5d3a-546e-59924dc71ae1&s=810590cd-0a6b-5f24-d5a4-bf96d07e06d9), on a test case that used a random matrix.  For reference, the log was
```text
test.python.circuit.test_isometry.TestIsometry.test_isometry_tolerance_02
-------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/home/vsts/work/1/s/test-job/lib/python3.7/site-packages/ddt.py", line 191, in wrapper
    return func(self, *args, **kwargs)

      File "/tmp/terra-tests/test/python/circuit/test_isometry.py", line 111, in test_isometry_tolerance
    self.assertTrue(matrix_equal(iso_from_circuit, iso, ignore_phase=True))

      File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/unittest/case.py", line 705, in assertTrue
    raise self.failureException(msg)

    AssertionError: False is not true
```
and the test case is on a data element `random_unitary(2).data`, which is generated at collection time.

### What should happen?

All generated data for tests should be done from a seeded position, so tests can be completely reproduced.

### Any suggestions?

There's perhaps not one magic bullet that we can swap everything to; it's no good just monkey-patching `random_unitary` during collection to fix a seed, because then it will always return the same matrix for the same size.  With `unittest`, I think the order of test collection is deterministic (because it's based on the import order), so in the `test_isometry` case, we could generate the arguments to `ddt.data` in one block off a single seed at collection time.  I haven't really audited the rest of the tests to see any other cases, though.

**Comment by levbishop** [comment]
This will also help with #7235

**Comment by jakelishman** [comment]
This particular example was fixed in #6559.  We always treat stochastic test failures as bugs to fix in the test suite, but we also open new issues whenever we see them, so I'll close this one.
