### ISSUE TITLE
Can't retrieve defaults of backend due to pulse_instruction KeyError

### ISSUE THREAD

**Issue by kt474** [Qiskit/qiskit#9092]
### Environment

- **Qiskit Terra version**: 0.22.2
- **Python version**: 3.9
- **Operating system**: Mac OS Monterey

### What is happening?

Retrieving backend defaults with `backend.defaults()` on certain backends like `ibm_kyiv` gives the following error:
Integration tests [here](https://github.com/Qiskit/qiskit-ibm-provider/actions/runs/3413274902/jobs/5680377124#step:5:687)
```
ERROR: test_backend_pulse_defaults (test.integration.test_backend.TestIBMBackend) (backend_name='ibm_kyiv')
Check the backend pulse defaults of each backend.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/qiskit-ibm-provider/qiskit-ibm-provider/test/integration/test_backend.py", line 74, in test_backend_pulse_defaults
    defaults = backend.defaults()
  File "/home/runner/work/qiskit-ibm-provider/qiskit-ibm-provider/qiskit_ibm_provider/ibm_backend.py", line 633, in defaults
    self._defaults = defaults_from_server_data(api_defaults)
  File "/home/runner/work/qiskit-ibm-provider/qiskit-ibm-provider/qiskit_ibm_provider/utils/json_decoder.py", line 44, in defaults_from_server_data
    return PulseDefaults.from_dict(defaults)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/qiskit/providers/models/pulsedefaults.py", line 279, in from_dict
    return cls(**in_data)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/qiskit/providers/models/pulsedefaults.py", line 206, in __init__
    pulse_insts = [self.converter(inst) for inst in inst.sequence]
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/qiskit/providers/models/pulsedefaults.py", line 206, in <listcomp>
    pulse_insts = [self.converter(inst) for inst in inst.sequence]
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/qiskit/qobj/converters/pulse_instruction.py", line 484, in __call__
    return method(self, instruction)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/qiskit/qobj/converters/pulse_instruction.py", line 727, in convert_parametric
    pulse = ParametricPulseShapes.to_type(instruction.pulse_shape)(
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/qiskit/qobj/converters/pulse_instruction.py", line 87, in to_type
    return getattr(library, cls[name].value)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/enum.py", line 432, in __getitem__
    return cls._member_map_[name]
KeyError: 'gaussian_square_drag'
```

### How can we reproduce the issue?

- Retrieve backend defaults from kyiv 

### What should happen?

Backend defaults are returned 

Apologies if this is in the wrong repo

**Comment by 1ucian0** [comment]
I dont have access to `ibm_kyiv` and I was unable to reproduce this with any of the fake backends in terra or the IBM backends in the open access program.

**Comment by jakelishman** [comment]
I can reproduce it with Kyiv on `main` Terra.  I'm not certain if this is an error in the decoders, or with the deployment of Kyiv - I know that `gaussian_square` and `drag` are individually correct pulse-shape names, but I don't think `gaussian_square_drag` is.  From a quick scan through the Terra git log, we've never had the string `gaussian_square_drag` committed to the repo, so I suspect the issue might be that Kyiv should have been deployed with the pulse shape `drag` instead?

I'm not very confident on this - perhaps @nkanazawa1989 or @wshanks can answer properly?

**Comment by nkanazawa1989** [comment]
Yes current qobj converter only supports `gaussian`, `gaussian_square`, `drag`, `constant`. I guess this is part of DDCX pulse but we don't have any PR for this symbolic pulse shape. Here is the PR for similar one https://github.com/Qiskit/qiskit-terra/pull/8757 so probably @miamico can contribute.

**Comment by wshanks** [comment]
I have been working on getting `gaussian_square_drag` and `gaussian_square_echo` supported by the backend code. I believe this counts as a misconfiguration of the backend at the moment. I think these pulses should be getting reported as Waveforms until the backend actually supports receiving these pulses. Even if they are added to qiskit.pulse like in #8757, I don't think the backend should be reporting them as parametric pulses until it can receive them as parametric pulses. Does that seem right, @nkanazawa1989?

**Comment by nkanazawa1989** [comment]
I'm not familiar with the backend code, but it sounds reasonable to use waveform payload until we support it.

**Comment by miamico** [comment]
Just seeing this conversation as I'm encountering the issue myself (on `ibm_ithaca`). Looking for a temporary fix until things are sorted out on the backend side

**Comment by nkanazawa1989** [comment]
There is nothing we can do on Qiskit frontend because it doesn't know the definition of pulse, i.e. it cannot generate waveform without knowing the envelope function. So what you can do as a temp fix is to catch this error and ignore it.

**Comment by jakelishman** [comment]
closing as obsolete with removal of pulse
